// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "count": string;
  readonly "indicator": string;
  readonly "list": string;
  readonly "panel": string;
  readonly "tab": string;
};

export default styles;
