// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "chevron": string;
  readonly "control": string;
  readonly "error": string;
  readonly "fieldset": string;
  readonly "form": string;
  readonly "label": string;
  readonly "legend": string;
  readonly "optional": string;
  readonly "root": string;
  readonly "select": string;
  readonly "selectWrap": string;
  readonly "textarea": string;
};

export default styles;
