import type { TailoredResume } from "../../../../shared/tailoring";
import {
  buildResumeTypstSource,
  cloneTailoredResume,
  removeLowestPriorityContent,
} from "./resume-document";

interface WorkerResponse {
  id: number;
  pdf?: ArrayBuffer;
  pageCount?: number;
  error?: string;
}

export interface CompiledResumeDocument {
  resume: TailoredResume;
  source: string;
  pdf: Uint8Array;
  pageCount: number;
}

export interface ResumePdfVerification {
  valid: boolean;
  missing: string[];
  extractedCharacters: number;
}

let worker: Worker | null = null;
let nextRequestId = 1;
const pending = new Map<number, {
  resolve: (value: WorkerResponse) => void;
  reject: (reason: Error) => void;
}>();

function compilerWorker(): Worker {
  if (worker) return worker;
  worker = new Worker(new URL("./resume-document.worker.ts", import.meta.url), { type: "module" });
  worker.addEventListener("message", (event: MessageEvent<WorkerResponse>) => {
    const request = pending.get(event.data.id);
    if (!request) return;
    pending.delete(event.data.id);
    if (event.data.error) request.reject(new Error(event.data.error));
    else request.resolve(event.data);
  });
  worker.addEventListener("error", () => {
    for (const request of pending.values()) request.reject(new Error("The resume compiler stopped unexpectedly."));
    pending.clear();
    worker?.terminate();
    worker = null;
  });
  return worker;
}

function compileSource(source: string): Promise<WorkerResponse> {
  const id = nextRequestId++;
  return new Promise((resolve, reject) => {
    pending.set(id, { resolve, reject });
    compilerWorker().postMessage({ id, source });
  });
}

export async function compileResumeDocument(
  initialResume: TailoredResume,
  priorityEvidenceIds: string[],
): Promise<CompiledResumeDocument> {
  let resume = cloneTailoredResume(initialResume);
  for (let attempt = 0; attempt < 40; attempt += 1) {
    const source = buildResumeTypstSource(resume);
    const result = await compileSource(source);
    if (!result.pdf || !result.pageCount) {
      throw new Error("The resume compiler returned an incomplete document.");
    }
    if (result.pageCount <= 1) {
      return { resume, source, pdf: new Uint8Array(result.pdf), pageCount: result.pageCount };
    }
    const removal = removeLowestPriorityContent(resume, priorityEvidenceIds);
    if (!removal.removed) {
      if (result.pageCount <= 2) {
        return { resume, source, pdf: new Uint8Array(result.pdf), pageCount: result.pageCount };
      }
      throw new Error("This resume needs more than two pages even at the minimum type size.");
    }
    resume = removal.resume;
  }
  throw new Error("The resume could not be fitted safely within two pages.");
}

function normalizedDocumentText(value: string): string {
  return value
    .normalize("NFKC")
    .toLocaleLowerCase()
    .replace(/[–—]/g, "-")
    .replace(/[^\p{L}\p{N}+#.%$-]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function expectedResumeText(resume: TailoredResume): Array<{ label: string; value: string }> {
  return [
    { label: "name", value: resume.contact.name },
    { label: "email", value: resume.contact.email },
    ...resume.experience.flatMap((entry) => [
      { label: `title: ${entry.title}`, value: entry.title },
      { label: `company: ${entry.company}`, value: entry.company },
      ...entry.bullets.map((bullet) => ({ label: `bullet: ${bullet.text.slice(0, 48)}`, value: bullet.text })),
    ]),
    ...resume.projects.flatMap((entry) => [
      { label: `project: ${entry.name}`, value: entry.name },
      ...entry.bullets.map((bullet) => ({ label: `bullet: ${bullet.text.slice(0, 48)}`, value: bullet.text })),
    ]),
    ...resume.education.map((entry) => ({ label: `school: ${entry.institution}`, value: entry.institution })),
  ].filter((item) => item.value.trim());
}

export function verifyResumeExtractedText(
  resume: TailoredResume,
  extractedText: string,
): ResumePdfVerification {
  const normalized = normalizedDocumentText(extractedText);
  const missing = expectedResumeText(resume)
    .filter((item) => !normalized.includes(normalizedDocumentText(item.value)))
    .map((item) => item.label);
  return {
    valid: normalized.length > 40 && missing.length === 0,
    missing,
    extractedCharacters: normalized.length,
  };
}

/** Re-open the exact generated bytes so export cannot succeed with a blank or incomplete PDF. */
export async function verifyCompiledResumePdf(
  pdfBytes: Uint8Array,
  resume: TailoredResume,
): Promise<ResumePdfVerification> {
  const [{ getDocument, GlobalWorkerOptions }, workerModule] = await Promise.all([
    import("pdfjs-dist"),
    import("pdfjs-dist/build/pdf.worker.mjs?url"),
  ]);
  GlobalWorkerOptions.workerSrc = workerModule.default;
  const document = await getDocument({ data: Uint8Array.from(pdfBytes) }).promise;
  const pageText: string[] = [];
  try {
    for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) {
      const page = await document.getPage(pageNumber);
      const content = await page.getTextContent();
      pageText.push(content.items.flatMap((item) => (
        item && typeof item === "object" && "str" in item && typeof item.str === "string"
          ? [item.str]
          : []
      )).join(" "));
    }
  } finally {
    await document.destroy();
  }
  return verifyResumeExtractedText(resume, pageText.join("\n"));
}
