// Builds the scripts the application browser injects into employer pages
// (src/platform/autofill/scripts.generated.ts) from the DOM sources in
// autofill/. Hermes can't turn functions back into source, so the strings are
// made here, by Bun. `--check` fails when the generated file is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { readForm, submittedPage, waitForForm } from "../autofill/form-reader";
import { fillForm, submitForm } from "../autofill/form-filler";

const target = fileURLToPath(new URL("../src/platform/autofill/scripts.generated.ts", import.meta.url));
const source = `// Generated by scripts/build-autofill.ts from autofill/. Do not edit.
// Run: bun apps/native/scripts/build-autofill.ts

/** Async function bodies run inside the form page; each returns a string. */
export const READ_FORM_BODY = ${JSON.stringify(`const submitted = ${submittedPage};
await (${waitForForm})(submitted);
return JSON.stringify({ submitted: submitted(), controls: (${readForm})() });`)};

/** \`fillForm(request)\`; called with one step (and the resume for uploads). */
export const FILL_FORM_FUNCTION = ${JSON.stringify(fillForm.toString())};

export const SUBMIT_FORM_BODY = ${JSON.stringify(`return JSON.stringify(await (${submitForm})());`)};
`;

if (process.argv.includes("--check")) {
  const current = (() => { try { return readFileSync(target, "utf8"); } catch { return ""; } })();
  if (current !== source) {
    console.error("apps/native autofill scripts are out of date. Run: bun apps/native/scripts/build-autofill.ts");
    process.exit(1);
  }
  console.log("Autofill scripts are up to date.");
} else {
  writeFileSync(target, source);
  console.log("Wrote src/platform/autofill/scripts.generated.ts");
}
