// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "action": string;
  readonly "copy": string;
  readonly "icon": string;
  readonly "root": string;
  readonly "title": string;
};

export default styles;
