// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "actions": string;
  readonly "backdrop": string;
  readonly "card": string;
  readonly "close": string;
  readonly "handle": string;
  readonly "header": string;
  readonly "sheet": string;
  readonly "sheetBody": string;
  readonly "sheetFooter": string;
  readonly "sheetHeader": string;
  readonly "subtitle": string;
  readonly "title": string;
  readonly "viewport": string;
};

export default styles;
