/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitRouteImport } from './routes/[_]kit'
import { Route as KitErrorRouteImport } from './routes/[_]kit-error'
import { Route as KitListRouteImport } from './routes/[_]kit-list'
import { Route as SplitRouteImport } from './routes/_split'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as YouRouteImport } from './routes/you'
import { Route as SplitIndexRouteImport } from './routes/_split.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminJevRouteImport } from './routes/admin.jev'
import { Route as AdminRunsRouteImport } from './routes/admin.runs'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as MyJobsAppliedRouteImport } from './routes/my-jobs.applied'
import { Route as MyJobsSavedRouteImport } from './routes/my-jobs.saved'
import { Route as TailorJobIdRouteImport } from './routes/tailor.$jobId'
import { Route as YouIndexRouteImport } from './routes/you.index'
import { Route as YouAccountRouteImport } from './routes/you.account'
import { Route as YouAlertsRouteImport } from './routes/you.alerts'
import { Route as YouAnswersRouteImport } from './routes/you.answers'
import { Route as YouCompaniesRouteImport } from './routes/you.companies'
import { Route as YouFeedbackRouteImport } from './routes/you.feedback'
import { Route as YouOperationsRouteImport } from './routes/you.operations'
import { Route as YouPreferencesRouteImport } from './routes/you.preferences'
import { Route as YouResumeRouteImport } from './routes/you.resume'
import { Route as YouTailoringRouteImport } from './routes/you.tailoring'
import { Route as SplitJobsJobIdRouteImport } from './routes/_split.jobs.$jobId'
import { Route as SplitLibraryAppliedRouteImport } from './routes/_split.library.applied'
import { Route as SplitLibrarySavedRouteImport } from './routes/_split.library.saved'

const KitRoute = KitRouteImport.update({
  id: '/_kit',
  path: '/_kit',
  getParentRoute: () => rootRouteImport,
} as any)
const KitErrorRoute = KitErrorRouteImport.update({
  id: '/_kit-error',
  path: '/_kit-error',
  getParentRoute: () => rootRouteImport,
} as any)
const KitListRoute = KitListRouteImport.update({
  id: '/_kit-list',
  path: '/_kit-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/_split',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitIndexRoute = SplitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SplitRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJevRoute = AdminJevRouteImport.update({
  id: '/jev',
  path: '/jev',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRunsRoute = AdminRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const MyJobsAppliedRoute = MyJobsAppliedRouteImport.update({
  id: '/my-jobs/applied',
  path: '/my-jobs/applied',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsSavedRoute = MyJobsSavedRouteImport.update({
  id: '/my-jobs/saved',
  path: '/my-jobs/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorJobIdRoute = TailorJobIdRouteImport.update({
  id: '/tailor/$jobId',
  path: '/tailor/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const YouIndexRoute = YouIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YouRoute,
} as any)
const YouAccountRoute = YouAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => YouRoute,
} as any)
const YouAlertsRoute = YouAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => YouRoute,
} as any)
const YouAnswersRoute = YouAnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => YouRoute,
} as any)
const YouCompaniesRoute = YouCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => YouRoute,
} as any)
const YouFeedbackRoute = YouFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => YouRoute,
} as any)
const YouOperationsRoute = YouOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => YouRoute,
} as any)
const YouPreferencesRoute = YouPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => YouRoute,
} as any)
const YouResumeRoute = YouResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => YouRoute,
} as any)
const YouTailoringRoute = YouTailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => YouRoute,
} as any)
const SplitJobsJobIdRoute = SplitJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => SplitRoute,
} as any)
const SplitLibraryAppliedRoute = SplitLibraryAppliedRouteImport.update({
  id: '/library/applied',
  path: '/library/applied',
  getParentRoute: () => SplitRoute,
} as any)
const SplitLibrarySavedRoute = SplitLibrarySavedRouteImport.update({
  id: '/library/saved',
  path: '/library/saved',
  getParentRoute: () => SplitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/_kit': typeof KitRoute
  '/_kit-error': typeof KitErrorRoute
  '/_kit-list': typeof KitListRoute
  '/': typeof SplitIndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/jev': typeof AdminJevRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/my-jobs/applied': typeof MyJobsAppliedRoute
  '/my-jobs/saved': typeof MyJobsSavedRoute
  '/tailor/$jobId': typeof TailorJobIdRoute
  '/you/account': typeof YouAccountRoute
  '/you/alerts': typeof YouAlertsRoute
  '/you/answers': typeof YouAnswersRoute
  '/you/companies': typeof YouCompaniesRoute
  '/you/feedback': typeof YouFeedbackRoute
  '/you/operations': typeof YouOperationsRoute
  '/you/preferences': typeof YouPreferencesRoute
  '/you/resume': typeof YouResumeRoute
  '/you/tailoring': typeof YouTailoringRoute
  '/admin/': typeof AdminIndexRoute
  '/you/': typeof YouIndexRoute
  '/jobs/$jobId': typeof SplitJobsJobIdRoute
  '/library/applied': typeof SplitLibraryAppliedRoute
  '/library/saved': typeof SplitLibrarySavedRoute
}
export interface FileRoutesByTo {
  '/_kit': typeof KitRoute
  '/_kit-error': typeof KitErrorRoute
  '/_kit-list': typeof KitListRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/jev': typeof AdminJevRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/my-jobs/applied': typeof MyJobsAppliedRoute
  '/my-jobs/saved': typeof MyJobsSavedRoute
  '/tailor/$jobId': typeof TailorJobIdRoute
  '/you/account': typeof YouAccountRoute
  '/you/alerts': typeof YouAlertsRoute
  '/you/answers': typeof YouAnswersRoute
  '/you/companies': typeof YouCompaniesRoute
  '/you/feedback': typeof YouFeedbackRoute
  '/you/operations': typeof YouOperationsRoute
  '/you/preferences': typeof YouPreferencesRoute
  '/you/resume': typeof YouResumeRoute
  '/you/tailoring': typeof YouTailoringRoute
  '/': typeof SplitIndexRoute
  '/admin': typeof AdminIndexRoute
  '/you': typeof YouIndexRoute
  '/jobs/$jobId': typeof SplitJobsJobIdRoute
  '/library/applied': typeof SplitLibraryAppliedRoute
  '/library/saved': typeof SplitLibrarySavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_kit': typeof KitRoute
  '/_kit-error': typeof KitErrorRoute
  '/_kit-list': typeof KitListRoute
  '/_split': typeof SplitRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/jev': typeof AdminJevRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/my-jobs/applied': typeof MyJobsAppliedRoute
  '/my-jobs/saved': typeof MyJobsSavedRoute
  '/tailor/$jobId': typeof TailorJobIdRoute
  '/you/account': typeof YouAccountRoute
  '/you/alerts': typeof YouAlertsRoute
  '/you/answers': typeof YouAnswersRoute
  '/you/companies': typeof YouCompaniesRoute
  '/you/feedback': typeof YouFeedbackRoute
  '/you/operations': typeof YouOperationsRoute
  '/you/preferences': typeof YouPreferencesRoute
  '/you/resume': typeof YouResumeRoute
  '/you/tailoring': typeof YouTailoringRoute
  '/_split/': typeof SplitIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/you/': typeof YouIndexRoute
  '/_split/jobs/$jobId': typeof SplitJobsJobIdRoute
  '/_split/library/applied': typeof SplitLibraryAppliedRoute
  '/_split/library/saved': typeof SplitLibrarySavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/_kit'
    | '/_kit-error'
    | '/_kit-list'
    | '/'
    | '/about'
    | '/admin'
    | '/companies'
    | '/library'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/support'
    | '/welcome'
    | '/you'
    | '/admin/inbox'
    | '/admin/jev'
    | '/admin/runs'
    | '/admin/sources'
    | '/my-jobs/applied'
    | '/my-jobs/saved'
    | '/tailor/$jobId'
    | '/you/account'
    | '/you/alerts'
    | '/you/answers'
    | '/you/companies'
    | '/you/feedback'
    | '/you/operations'
    | '/you/preferences'
    | '/you/resume'
    | '/you/tailoring'
    | '/admin/'
    | '/you/'
    | '/jobs/$jobId'
    | '/library/applied'
    | '/library/saved'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/_kit'
    | '/_kit-error'
    | '/_kit-list'
    | '/about'
    | '/companies'
    | '/library'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/support'
    | '/welcome'
    | '/admin/inbox'
    | '/admin/jev'
    | '/admin/runs'
    | '/admin/sources'
    | '/my-jobs/applied'
    | '/my-jobs/saved'
    | '/tailor/$jobId'
    | '/you/account'
    | '/you/alerts'
    | '/you/answers'
    | '/you/companies'
    | '/you/feedback'
    | '/you/operations'
    | '/you/preferences'
    | '/you/resume'
    | '/you/tailoring'
    | '/'
    | '/admin'
    | '/you'
    | '/jobs/$jobId'
    | '/library/applied'
    | '/library/saved'
  id:
    | '__root__'
    | '/_kit'
    | '/_kit-error'
    | '/_kit-list'
    | '/_split'
    | '/about'
    | '/admin'
    | '/companies'
    | '/library'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/support'
    | '/welcome'
    | '/you'
    | '/admin/inbox'
    | '/admin/jev'
    | '/admin/runs'
    | '/admin/sources'
    | '/my-jobs/applied'
    | '/my-jobs/saved'
    | '/tailor/$jobId'
    | '/you/account'
    | '/you/alerts'
    | '/you/answers'
    | '/you/companies'
    | '/you/feedback'
    | '/you/operations'
    | '/you/preferences'
    | '/you/resume'
    | '/you/tailoring'
    | '/_split/'
    | '/admin/'
    | '/you/'
    | '/_split/jobs/$jobId'
    | '/_split/library/applied'
    | '/_split/library/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KitRoute: typeof KitRoute
  KitErrorRoute: typeof KitErrorRoute
  KitListRoute: typeof KitListRoute
  SplitRoute: typeof SplitRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompaniesRoute: typeof CompaniesRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  WelcomeRoute: typeof WelcomeRoute
  YouRoute: typeof YouRouteWithChildren
  MyJobsAppliedRoute: typeof MyJobsAppliedRoute
  MyJobsSavedRoute: typeof MyJobsSavedRoute
  TailorJobIdRoute: typeof TailorJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kit': {
      id: '/_kit'
      path: '/_kit'
      fullPath: '/_kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kit-error': {
      id: '/_kit-error'
      path: '/_kit-error'
      fullPath: '/_kit-error'
      preLoaderRoute: typeof KitErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kit-list': {
      id: '/_kit-list'
      path: '/_kit-list'
      fullPath: '/_kit-list'
      preLoaderRoute: typeof KitListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_split': {
      id: '/_split'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_split/': {
      id: '/_split/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SplitIndexRouteImport
      parentRoute: typeof SplitRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jev': {
      id: '/admin/jev'
      path: '/jev'
      fullPath: '/admin/jev'
      preLoaderRoute: typeof AdminJevRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/runs': {
      id: '/admin/runs'
      path: '/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminRunsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/my-jobs/applied': {
      id: '/my-jobs/applied'
      path: '/my-jobs/applied'
      fullPath: '/my-jobs/applied'
      preLoaderRoute: typeof MyJobsAppliedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs/saved': {
      id: '/my-jobs/saved'
      path: '/my-jobs/saved'
      fullPath: '/my-jobs/saved'
      preLoaderRoute: typeof MyJobsSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor/$jobId': {
      id: '/tailor/$jobId'
      path: '/tailor/$jobId'
      fullPath: '/tailor/$jobId'
      preLoaderRoute: typeof TailorJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you/': {
      id: '/you/'
      path: '/'
      fullPath: '/you/'
      preLoaderRoute: typeof YouIndexRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/account': {
      id: '/you/account'
      path: '/account'
      fullPath: '/you/account'
      preLoaderRoute: typeof YouAccountRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/alerts': {
      id: '/you/alerts'
      path: '/alerts'
      fullPath: '/you/alerts'
      preLoaderRoute: typeof YouAlertsRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/answers': {
      id: '/you/answers'
      path: '/answers'
      fullPath: '/you/answers'
      preLoaderRoute: typeof YouAnswersRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/companies': {
      id: '/you/companies'
      path: '/companies'
      fullPath: '/you/companies'
      preLoaderRoute: typeof YouCompaniesRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/feedback': {
      id: '/you/feedback'
      path: '/feedback'
      fullPath: '/you/feedback'
      preLoaderRoute: typeof YouFeedbackRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/operations': {
      id: '/you/operations'
      path: '/operations'
      fullPath: '/you/operations'
      preLoaderRoute: typeof YouOperationsRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/preferences': {
      id: '/you/preferences'
      path: '/preferences'
      fullPath: '/you/preferences'
      preLoaderRoute: typeof YouPreferencesRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/resume': {
      id: '/you/resume'
      path: '/resume'
      fullPath: '/you/resume'
      preLoaderRoute: typeof YouResumeRouteImport
      parentRoute: typeof YouRoute
    }
    '/you/tailoring': {
      id: '/you/tailoring'
      path: '/tailoring'
      fullPath: '/you/tailoring'
      preLoaderRoute: typeof YouTailoringRouteImport
      parentRoute: typeof YouRoute
    }
    '/_split/jobs/$jobId': {
      id: '/_split/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof SplitJobsJobIdRouteImport
      parentRoute: typeof SplitRoute
    }
    '/_split/library/applied': {
      id: '/_split/library/applied'
      path: '/library/applied'
      fullPath: '/library/applied'
      preLoaderRoute: typeof SplitLibraryAppliedRouteImport
      parentRoute: typeof SplitRoute
    }
    '/_split/library/saved': {
      id: '/_split/library/saved'
      path: '/library/saved'
      fullPath: '/library/saved'
      preLoaderRoute: typeof SplitLibrarySavedRouteImport
      parentRoute: typeof SplitRoute
    }
  }
}

interface SplitRouteChildren {
  SplitIndexRoute: typeof SplitIndexRoute
  SplitJobsJobIdRoute: typeof SplitJobsJobIdRoute
  SplitLibraryAppliedRoute: typeof SplitLibraryAppliedRoute
  SplitLibrarySavedRoute: typeof SplitLibrarySavedRoute
}

const SplitRouteChildren: SplitRouteChildren = {
  SplitIndexRoute: SplitIndexRoute,
  SplitJobsJobIdRoute: SplitJobsJobIdRoute,
  SplitLibraryAppliedRoute: SplitLibraryAppliedRoute,
  SplitLibrarySavedRoute: SplitLibrarySavedRoute,
}

const SplitRouteWithChildren = SplitRoute._addFileChildren(SplitRouteChildren)

interface AdminRouteChildren {
  AdminInboxRoute: typeof AdminInboxRoute
  AdminJevRoute: typeof AdminJevRoute
  AdminRunsRoute: typeof AdminRunsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInboxRoute: AdminInboxRoute,
  AdminJevRoute: AdminJevRoute,
  AdminRunsRoute: AdminRunsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface YouRouteChildren {
  YouAccountRoute: typeof YouAccountRoute
  YouAlertsRoute: typeof YouAlertsRoute
  YouAnswersRoute: typeof YouAnswersRoute
  YouCompaniesRoute: typeof YouCompaniesRoute
  YouFeedbackRoute: typeof YouFeedbackRoute
  YouOperationsRoute: typeof YouOperationsRoute
  YouPreferencesRoute: typeof YouPreferencesRoute
  YouResumeRoute: typeof YouResumeRoute
  YouTailoringRoute: typeof YouTailoringRoute
  YouIndexRoute: typeof YouIndexRoute
}

const YouRouteChildren: YouRouteChildren = {
  YouAccountRoute: YouAccountRoute,
  YouAlertsRoute: YouAlertsRoute,
  YouAnswersRoute: YouAnswersRoute,
  YouCompaniesRoute: YouCompaniesRoute,
  YouFeedbackRoute: YouFeedbackRoute,
  YouOperationsRoute: YouOperationsRoute,
  YouPreferencesRoute: YouPreferencesRoute,
  YouResumeRoute: YouResumeRoute,
  YouTailoringRoute: YouTailoringRoute,
  YouIndexRoute: YouIndexRoute,
}

const YouRouteWithChildren = YouRoute._addFileChildren(YouRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  KitRoute: KitRoute,
  KitErrorRoute: KitErrorRoute,
  KitListRoute: KitListRoute,
  SplitRoute: SplitRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CompaniesRoute: CompaniesRoute,
  LibraryRoute: LibraryRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  WelcomeRoute: WelcomeRoute,
  YouRoute: YouRouteWithChildren,
  MyJobsAppliedRoute: MyJobsAppliedRoute,
  MyJobsSavedRoute: MyJobsSavedRoute,
  TailorJobIdRoute: TailorJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
