/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 86cad6192e992c711f9c47b1b6ffbc3d)
interface __BaseEnv_CloudflareBindings {
	RESUME_BUCKET: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	SOURCE_POLL_PRIORITY_QUEUE: Queue;
	SOURCE_POLL_QUEUE: Queue;
	NOTIFY_QUEUE: Queue;
	AI: Ai;
	ASSETS: Fetcher;
	VAPID_SUBJECT: string;
	VAPID_PUBLIC_KEY: string;
	EMAIL_FROM_NAME: string;
	EMAIL_FROM_ADDRESS: string;
	WORKERS_AI_MODEL: string;
	QUEUE_POLLING_TIERS: string;
	JOB_CLASSIFICATION_SHADOW: string;
	AI_MONTHLY_BUDGET_USD: string;
	APPLE_APP_ID: string;
	APPLE_TEAM_ID: string;
	APNS_TEAM_ID: string;
	APNS_BUNDLE_ID: string;
	APNS_KEY_ID: string;
	VAPID_PRIVATE_KEY: string;
	APNS_PRIVATE_KEY: string;
	APPLE_SIGN_IN_CLIENT_ID: string;
	APPLE_SIGN_IN_KEY_ID: string;
	APPLE_SIGN_IN_PRIVATE_KEY: string;
	APPLE_TOKEN_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VAPID_SUBJECT" | "VAPID_PUBLIC_KEY" | "EMAIL_FROM_NAME" | "EMAIL_FROM_ADDRESS" | "WORKERS_AI_MODEL" | "QUEUE_POLLING_TIERS" | "JOB_CLASSIFICATION_SHADOW" | "AI_MONTHLY_BUDGET_USD" | "APPLE_APP_ID" | "APPLE_TEAM_ID" | "APNS_TEAM_ID" | "APNS_BUNDLE_ID" | "APNS_KEY_ID" | "VAPID_PRIVATE_KEY" | "APNS_PRIVATE_KEY" | "APPLE_SIGN_IN_CLIENT_ID" | "APPLE_SIGN_IN_KEY_ID" | "APPLE_SIGN_IN_PRIVATE_KEY" | "APPLE_TOKEN_ENCRYPTION_KEY">> {}
}
