// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "actions": string;
  readonly "attention": string;
  readonly "copy": string;
  readonly "count": string;
  readonly "error": string;
  readonly "filters": string;
  readonly "item": string;
  readonly "meta": string;
  readonly "more": string;
  readonly "name": string;
  readonly "pair": string;
  readonly "request": string;
  readonly "row": string;
  readonly "slug": string;
  readonly "summary": string;
  readonly "toolbar": string;
};

export default styles;
