/**
 * Generated by scripts/generate.ts from src/tokens.ts. Do not edit by hand.
 *
 * Colors convert to hex/rgba and lengths to point numbers at the 16px web root.
 * Safe-area and calc() compositions are web-only and intentionally absent;
 * native supplies safe areas through the platform. Modes mirror the web
 * cascade: `light`, `contrast` and `lightContrast` override `dark`.
 * The native kit (6.2) may reshape this data, but token names stay aligned
 * with the web kit's prop values.
 */
import type { ColorToken, ShadowToken, ThemeName } from "./types";

export const breakpoints = {
  wide: 900,
} as const;

export const color = {
    dark: {
      bg: "#0e0e10",
      "bg-elev": "#17171a",
      "bg-sunken": "#08080a",
      ink: "#f3f3f5",
      "ink-2": "#c3c4c7",
      "ink-3": "#98989c",
      "ink-4": "#86868a",
      line: "#2b2b2e",
      "line-2": "#3d3d41",
      "message-border": "rgba(255, 255, 255, 0.13)",
      paper: "#ffffff",
      accent: "#ff8cc5",
      "accent-fill": "#ff8cc5",
      "accent-ink": "#110c0e",
      "accent-soft": "#361726",
      "accent-soft-ink": "#ffb9d9",
      "selection-bg": "#e1e1e4",
      "selection-ink": "#111114",
      good: "#5ec077",
      "good-soft": "#112315",
      warn: "#efac44",
      bad: "#fd736d",
      "bad-soft": "#331715",
      "control-bg": "#222226",
      "input-bg": "#222226",
      "control-border": "#3f3f43",
      "control-active-bg": "#0a0a0c",
      "control-active-ink": "#f8f8fa",
      "control-selected-bg": "#3f3f43",
      "control-selected-ink": "#f8f8fa",
      "control-selected-border": "#636367",
      scrim: "rgba(0, 0, 0, 0.52)",
      "image-outline": "rgba(255, 255, 255, 0.1)",
      "nav-dim": "#000000",
    },
    light: {
      bg: "#fbfaf9",
      "bg-elev": "#ffffff",
      "bg-sunken": "#f3f2f0",
      ink: "#111114",
      "ink-2": "#37383b",
      "ink-3": "#57585b",
      "ink-4": "#68686c",
      line: "#e1dfdd",
      "line-2": "#c7c5c3",
      "message-border": "rgba(0, 0, 0, 0.14)",
      paper: "#ffffff",
      accent: "#c82e88",
      "accent-fill": "#ff8cc5",
      "accent-ink": "#110c0e",
      "accent-soft": "#feeff5",
      "accent-soft-ink": "#7d1453",
      "selection-bg": "#1a1a1d",
      "selection-ink": "#fcfcfa",
      good: "#007132",
      "good-soft": "#e5f5e7",
      warn: "#916102",
      bad: "#b32228",
      "bad-soft": "#ffebe9",
      "control-bg": "#ecebea",
      "input-bg": "#ecebea",
      "control-border": "#cac9c6",
      "control-active-bg": "#ffffff",
      "control-active-ink": "#111114",
      "control-selected-bg": "#222226",
      "control-selected-ink": "#fcfcfa",
      "control-selected-border": "#222226",
      scrim: "rgba(5, 6, 8, 0.38)",
      "image-outline": "rgba(0, 0, 0, 0.1)",
      "nav-dim": "#050608",
    },
    contrast: {
      bg: "#0e0e10",
      "bg-elev": "#17171a",
      "bg-sunken": "#08080a",
      ink: "#f3f3f5",
      "ink-2": "#d7d7db",
      "ink-3": "#b0b1b5",
      "ink-4": "#9e9ea2",
      line: "#424245",
      "line-2": "#5d5d61",
      "message-border": "rgba(255, 255, 255, 0.13)",
      paper: "#ffffff",
      accent: "#ff8cc5",
      "accent-fill": "#ff8cc5",
      "accent-ink": "#110c0e",
      "accent-soft": "#361726",
      "accent-soft-ink": "#ffb9d9",
      "selection-bg": "#e1e1e4",
      "selection-ink": "#111114",
      good: "#5ec077",
      "good-soft": "#112315",
      warn: "#efac44",
      bad: "#fd736d",
      "bad-soft": "#331715",
      "control-bg": "#222226",
      "input-bg": "#222226",
      "control-border": "#636367",
      "control-active-bg": "#0a0a0c",
      "control-active-ink": "#f8f8fa",
      "control-selected-bg": "#3f3f43",
      "control-selected-ink": "#f8f8fa",
      "control-selected-border": "#636367",
      scrim: "rgba(0, 0, 0, 0.52)",
      "image-outline": "rgba(255, 255, 255, 0.1)",
      "nav-dim": "#000000",
    },
    lightContrast: {
      bg: "#fbfaf9",
      "bg-elev": "#ffffff",
      "bg-sunken": "#f3f2f0",
      ink: "#111114",
      "ink-2": "#212124",
      "ink-3": "#47474b",
      "ink-4": "#57585b",
      line: "#c5c4c2",
      "line-2": "#a6a4a2",
      "message-border": "rgba(0, 0, 0, 0.14)",
      paper: "#ffffff",
      accent: "#c82e88",
      "accent-fill": "#ff8cc5",
      "accent-ink": "#110c0e",
      "accent-soft": "#feeff5",
      "accent-soft-ink": "#7d1453",
      "selection-bg": "#1a1a1d",
      "selection-ink": "#fcfcfa",
      good: "#007132",
      "good-soft": "#e5f5e7",
      warn: "#916102",
      bad: "#b32228",
      "bad-soft": "#ffebe9",
      "control-bg": "#ecebea",
      "input-bg": "#ecebea",
      "control-border": "#a6a4a2",
      "control-active-bg": "#ffffff",
      "control-active-ink": "#111114",
      "control-selected-bg": "#222226",
      "control-selected-ink": "#fcfcfa",
      "control-selected-border": "#222226",
      scrim: "rgba(5, 6, 8, 0.38)",
      "image-outline": "rgba(0, 0, 0, 0.1)",
      "nav-dim": "#050608",
    },
} satisfies Record<ThemeName, Record<ColorToken, string>>;

export interface NativeShadow {
  x: number;
  y: number;
  blur: number;
  color: string;
}

export const shadow = {
    dark: {
      "control-active": {
        x: 0,
        y: 1,
        blur: 4,
        color: "rgba(0, 0, 0, 0.3)",
      },
      overlay: {
        x: 0,
        y: 18,
        blur: 54,
        color: "rgba(0, 0, 0, 0.32)",
      },
      "overlay-lg": {
        x: 0,
        y: 24,
        blur: 80,
        color: "rgba(0, 0, 0, 0.36)",
      },
      toast: {
        x: 0,
        y: 12,
        blur: 36,
        color: "rgba(0, 0, 0, 0.25)",
      },
      sheet: {
        x: 0,
        y: -8,
        blur: 32,
        color: "rgba(0, 0, 0, 0.3)",
      },
    },
    light: {
      "control-active": {
        x: 0,
        y: 1,
        blur: 4,
        color: "rgba(0, 0, 0, 0.1)",
      },
      overlay: {
        x: 0,
        y: 20,
        blur: 60,
        color: "rgba(13, 13, 17, 0.16)",
      },
      "overlay-lg": {
        x: 0,
        y: 24,
        blur: 80,
        color: "rgba(13, 13, 17, 0.18)",
      },
      toast: {
        x: 0,
        y: 12,
        blur: 34,
        color: "rgba(13, 13, 17, 0.14)",
      },
      sheet: {
        x: 0,
        y: -8,
        blur: 32,
        color: "rgba(13, 13, 17, 0.14)",
      },
    },
    contrast: {
      "control-active": {
        x: 0,
        y: 1,
        blur: 4,
        color: "rgba(0, 0, 0, 0.3)",
      },
      overlay: {
        x: 0,
        y: 18,
        blur: 54,
        color: "rgba(0, 0, 0, 0.32)",
      },
      "overlay-lg": {
        x: 0,
        y: 24,
        blur: 80,
        color: "rgba(0, 0, 0, 0.36)",
      },
      toast: {
        x: 0,
        y: 12,
        blur: 36,
        color: "rgba(0, 0, 0, 0.25)",
      },
      sheet: {
        x: 0,
        y: -8,
        blur: 32,
        color: "rgba(0, 0, 0, 0.3)",
      },
    },
    lightContrast: {
      "control-active": {
        x: 0,
        y: 1,
        blur: 4,
        color: "rgba(0, 0, 0, 0.1)",
      },
      overlay: {
        x: 0,
        y: 20,
        blur: 60,
        color: "rgba(13, 13, 17, 0.16)",
      },
      "overlay-lg": {
        x: 0,
        y: 24,
        blur: 80,
        color: "rgba(13, 13, 17, 0.18)",
      },
      toast: {
        x: 0,
        y: 12,
        blur: 34,
        color: "rgba(13, 13, 17, 0.14)",
      },
      sheet: {
        x: 0,
        y: -8,
        blur: 32,
        color: "rgba(13, 13, 17, 0.14)",
      },
    },
} satisfies Record<ThemeName, Record<ShadowToken, NativeShadow>>;

export const radius = {
  xs: 6,
  sm: 8,
  md: 10,
  lg: 14,
  xl: 20,
  full: 999,
} as const;

export const space = {
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 20,
  "6": 24,
  "8": 32,
  "10": 40,
} as const;

export const fontSize = {
  "3xs": 11,
  "2xs": 12,
  xs: 13,
  sm: 14,
  md: 16,
  base: 16,
  lg: 18,
  xl: 22,
  "2xl": 24,
  "4xl": 32,
  "root-title": 40,
} as const;

export const fontFamily = {
  heading: "\"Pinkslip Founders Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
  display: "\"Pinkslip Untitled Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
  sans: "\"Pinkslip Untitled Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
  mono: "ui-monospace, \"SF Mono\", SFMono-Regular, Menlo, Consolas, monospace",
} as const;

export const leading = {
  body: 1.46,
  "root-title": 1.12,
  "screen-title": 1.14,
} as const;

export const tracking = {
  "root-title": -0.012,
  "screen-title": -0.01,
} as const;

export const duration = {
  instant: 140,
  fast: 180,
  standard: 220,
} as const;

export const ease = {
  standard: [0.2, 0.7, 0.2, 1],
} as const;

export const zIndex = {
  navigation: 20,
  overlay: 40,
  toast: 60,
} as const;

export const layout = {
  "app-mobile-width": 480,
  "app-reading-width": 720,
  "app-nav-wide": 232,
  "screen-gutter": 16,
  "screen-nav-height": 56,
  "mobile-tab-bar-height": 58,
} as const;

export const sizing = {
  "tap-min": 44,
  "control-height": 48,
  "control-height-compact": 40,
  "control-height-small": 32,
  "pill-height": 32,
} as const;
