/**
 * Generated by scripts/generate.ts from src/tokens.ts. Do not edit by hand.
 *
 * Prop-value unions shared by the web and native kits, so an off-scale value
 * is a type error on both platforms.
 */
export type ThemeName = "dark" | "light" | "contrast" | "lightContrast";
export type BreakpointToken = "wide";
export type ColorToken = "bg" | "bg-elev" | "bg-sunken" | "ink" | "ink-2" | "ink-3" | "ink-4" | "line" | "line-2" | "message-border" | "paper" | "accent" | "accent-fill" | "accent-ink" | "accent-soft" | "accent-soft-ink" | "selection-bg" | "selection-ink" | "good" | "good-soft" | "warn" | "bad" | "bad-soft" | "control-bg" | "input-bg" | "control-border" | "control-active-bg" | "control-active-ink" | "control-selected-bg" | "control-selected-ink" | "control-selected-border" | "scrim" | "image-outline" | "nav-dim";
export type ShadowToken = "control-active" | "overlay" | "overlay-lg" | "toast" | "sheet";
export type RadiusToken = "xs" | "sm" | "md" | "lg" | "xl" | "full";
export type SpaceToken = "1" | "2" | "3" | "4" | "5" | "6" | "8" | "10";
export type FontSizeToken = "3xs" | "2xs" | "xs" | "sm" | "md" | "base" | "lg" | "xl" | "2xl" | "4xl" | "root-title";
export type DurationToken = "instant" | "fast" | "standard";
export type EaseToken = "standard";
export type ZIndexToken = "navigation" | "overlay" | "toast";
export type FontFamilyToken = "heading" | "display" | "sans" | "mono";
export type LeadingToken = "body" | "root-title" | "screen-title";
export type TrackingToken = "root-title" | "screen-title";
