// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "indicator": string;
  readonly "root": string;
  readonly "step": string;
  readonly "track": string;
};

export default styles;
