import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

/* `apps/mobile/ios` is generated by `expo prebuild` and then edited by hand.
   These checks catch a later prebuild quietly undoing those edits. */

const root = resolve(import.meta.dir, "..", "apps/mobile");

function source(path: string): string {
  return readFileSync(resolve(root, path), "utf8");
}

describe("mobile iOS project", () => {
  test("adopts the scene life cycle iOS 27 requires to launch", () => {
    const plist = source("ios/Pinkslip/Info.plist");
    const appDelegate = source("ios/Pinkslip/AppDelegate.swift");
    const project = source("ios/Pinkslip.xcodeproj/project.pbxproj");

    expect(existsSync(resolve(root, "ios/Pinkslip/SceneDelegate.swift"))).toBe(true);
    expect(source("ios/Pinkslip/SceneDelegate.swift")).toContain("class SceneDelegate: ExpoAppSceneDelegate");
    expect(plist).toContain("<key>UIApplicationSceneManifest</key>");
    expect(plist).toContain("<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>");
    expect(appDelegate).toContain("ExpoReactNativeFactoryProvider");
    expect(appDelegate).not.toContain("startReactNative");
    expect(project).toContain("SceneDelegate.swift in Sources");
  });

  test("ships the version in app.json", () => {
    const { version } = JSON.parse(source("app.json")).expo as { version: string };
    const plist = source("ios/Pinkslip/Info.plist");
    const project = source("ios/Pinkslip.xcodeproj/project.pbxproj");

    expect(plist).toContain(`<key>CFBundleShortVersionString</key>\n    <string>${version}</string>`);
    expect(project.match(/MARKETING_VERSION = ([^;]+);/g)).toEqual([
      `MARKETING_VERSION = ${version};`,
      `MARKETING_VERSION = ${version};`,
    ]);
  });

  test("keeps the Capacitor app's identity and capabilities", () => {
    const entitlements = source("ios/Pinkslip/Pinkslip.entitlements");
    const project = source("ios/Pinkslip.xcodeproj/project.pbxproj");

    expect(project).toContain('PRODUCT_BUNDLE_IDENTIFIER = "dev.alip.pinkslip";');
    expect(project).toContain("DEVELOPMENT_TEAM = KV876H8952;");
    expect(entitlements).toContain("com.apple.developer.applesignin");
    expect(entitlements).toContain("<string>applinks:pinkslip.work</string>");
    expect(entitlements).toContain("<key>aps-environment</key>");
  });
});
