import { describe, expect, test } from "bun:test";
import { extractClassNames, renderDeclaration } from "../scripts/generate-webapp-css-modules";

describe("css module declarations", () => {
  test("extracts local class names and keyframes, ignoring non-classes", () => {
    const css = `
      /* .commented { } */
      .a { color: var(--x); }
      .b.c { }
      .a { }
      @media (min-width: 900px) { .d { } }
      :global(.global) .e { }
      .f { margin: 0.5rem; background: url(../images/a.svg); }
      @keyframes fade { }
    `;
    expect(extractClassNames(css)).toEqual(["a", "b", "c", "d", "e", "f", "fade"]);
  });

  test("renders a readonly declaration", () => {
    expect(renderDeclaration(["a", "b"])).toBe([
      "// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.",
      "declare const styles: {",
      '  readonly "a": string;',
      '  readonly "b": string;',
      "};",
      "",
      "export default styles;",
      "",
    ].join("\n"));
  });
});
