// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "reveal": string;
  readonly "root": string;
  readonly "spin": string;
};

export default styles;
