// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "about": string;
  readonly "actionBar": string;
  readonly "actionStatus": string;
  readonly "actions": string;
  readonly "companyLine": string;
  readonly "description": string;
  readonly "descriptionSkeleton": string;
  readonly "facts": string;
  readonly "heading": string;
  readonly "identity": string;
  readonly "meta": string;
  readonly "missing": string;
  readonly "original": string;
  readonly "root": string;
  readonly "stepper": string;
  readonly "textButton": string;
};

export default styles;
