// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "detail": string;
  readonly "list": string;
  readonly "placeholder": string;
  readonly "placeholderMark": string;
  readonly "placeholderMessage": string;
  readonly "root": string;
};

export default styles;
