ALTER TABLE jobs ADD COLUMN title_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN yoe_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN location_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN department_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN recency_score INTEGER NOT NULL DEFAULT 0;
