-- Comprehensive company seed expansion.
--
-- Keep this migration aligned with the current companies schema:
--   id, name, ats_type, ats_slug, website, enabled, added_at
--
-- Unsupported ATS guesses from the source list (workday/custom) are intentionally
-- coerced to greenhouse so they can be surfaced and corrected from the UI after
-- the first poll.

CREATE TABLE seed_0021_companies (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  ats_type TEXT NOT NULL CHECK (ats_type IN ('greenhouse', 'lever', 'ashby', 'custom')),
  ats_slug TEXT NOT NULL
);

INSERT INTO seed_0021_companies (id, name, ats_type, ats_slug) VALUES
  ('seed-0021-skildai', 'Skild AI', 'greenhouse', 'skildai-careers'),
  ('seed-0021-figure', 'Figure', 'greenhouse', 'figureai'),
  ('seed-0021-wayve', 'Wayve', 'greenhouse', 'wayve'),
  ('seed-0021-aurora', 'Aurora Innovation', 'greenhouse', 'aurorainnovation'),
  ('seed-0021-waymo', 'Waymo', 'greenhouse', 'waymo'),
  ('seed-0021-appliedintuition', 'Applied Intuition', 'greenhouse', 'appliedintuition'),
  ('seed-0021-shieldai', 'Shield AI', 'lever', 'shieldai'),
  ('seed-0021-1x', '1X Technologies', 'ashby', '1x'),
  ('seed-0021-apptronik', 'Apptronik', 'greenhouse', 'apptronik'),
  ('seed-0021-bostondynamics', 'Boston Dynamics', 'greenhouse', 'bostondynamics'),
  ('seed-0021-palantir', 'Palantir', 'greenhouse', 'palantir'),
  ('seed-0021-saronic', 'Saronic', 'ashby', 'saronic'),
  ('seed-0021-hadrian', 'Hadrian', 'ashby', 'hadrian'),
  ('seed-0021-vannevarlabs', 'Vannevar Labs', 'ashby', 'vannevarlabs'),
  ('seed-0021-episci', 'EpiSci', 'greenhouse', 'episci'),
  ('seed-0021-isomorphiclabs', 'Isomorphic Labs', 'greenhouse', 'isomorphiclabs'),
  ('seed-0021-inceptive', 'Inceptive', 'ashby', 'inceptive'),
  ('seed-0021-recursion', 'Recursion', 'greenhouse', 'recursionpharmaceuticals'),
  ('seed-0021-insitro', 'Insitro', 'greenhouse', 'insitro'),
  ('seed-0021-generatebiomedicines', 'Generate Biomedicines', 'greenhouse', 'generatebiomedicines'),
  ('seed-0021-xaira', 'Xaira Therapeutics', 'ashby', 'xaira'),
  ('seed-0021-hume', 'Hume AI', 'greenhouse', 'humeai'),
  ('seed-0021-sesame', 'Sesame', 'ashby', 'sesame'),
  ('seed-0021-wispr', 'Wispr Flow', 'ashby', 'wisprflow'),
  ('seed-0021-tavily', 'Tavily', 'ashby', 'tavily'),
  ('seed-0021-firecrawl', 'Firecrawl', 'ashby', 'firecrawl'),
  ('seed-0021-youcom', 'You.com', 'greenhouse', 'youcom'),
  ('seed-0021-brave', 'Brave Software', 'greenhouse', 'brave'),
  ('seed-0021-kagi', 'Kagi', 'greenhouse', 'kagi'),
  ('seed-0021-multion', 'MultiOn', 'ashby', 'multion'),
  ('seed-0021-browserbase', 'Browserbase', 'ashby', 'browserbase'),
  ('seed-0021-public', 'Public.com', 'greenhouse', 'public'),
  ('seed-0021-etoro', 'eToro', 'greenhouse', 'etoro'),
  ('seed-0021-webull', 'Webull', 'greenhouse', 'webull'),
  ('seed-0021-m1finance', 'M1 Finance', 'greenhouse', 'm1finance'),
  ('seed-0021-wealthfront', 'Wealthfront', 'greenhouse', 'wealthfrontcareers'),
  ('seed-0021-betterment', 'Betterment', 'greenhouse', 'betterment'),
  ('seed-0021-composer', 'Composer', 'ashby', 'composer'),
  ('seed-0021-alpaca', 'Alpaca', 'greenhouse', 'alpaca'),
  ('seed-0021-phantom', 'Phantom', 'ashby', 'phantom'),
  ('seed-0021-helius', 'Helius', 'ashby', 'helius'),
  ('seed-0021-alchemy', 'Alchemy', 'greenhouse', 'alchemy'),
  ('seed-0021-quicknode', 'QuickNode', 'greenhouse', 'quicknode'),
  ('seed-0021-magiceden', 'Magic Eden', 'greenhouse', 'magiceden'),
  ('seed-0021-opensea', 'OpenSea', 'greenhouse', 'opensea'),
  ('seed-0021-uniswaplabs', 'Uniswap Labs', 'greenhouse', 'uniswaplabs'),
  ('seed-0021-aptoslabs', 'Aptos Labs', 'greenhouse', 'aptoslabs'),
  ('seed-0021-mystenlabs', 'Mysten Labs', 'ashby', 'mystenlabs'),
  ('seed-0021-polygonlabs', 'Polygon Labs', 'greenhouse', 'polygonlabs'),
  ('seed-0021-chainlinklabs', 'Chainlink Labs', 'greenhouse', 'chainlinklabs'),
  ('seed-0021-circle', 'Circle', 'greenhouse', 'circle'),
  ('seed-0021-kraken', 'Kraken', 'greenhouse', 'payward'),
  ('seed-0021-gemini', 'Gemini', 'greenhouse', 'gemini'),
  ('seed-0021-dynamic', 'Dynamic', 'ashby', 'dynamic'),
  ('seed-0021-turnkey', 'Turnkey', 'ashby', 'turnkey'),
  ('seed-0021-pilot', 'Pilot', 'greenhouse', 'pilot'),
  ('seed-0021-drata', 'Drata', 'greenhouse', 'drata'),
  ('seed-0021-persona', 'Persona', 'greenhouse', 'withpersona'),
  ('seed-0021-alloy', 'Alloy', 'greenhouse', 'alloy'),
  ('seed-0021-unit', 'Unit', 'greenhouse', 'unit'),
  ('seed-0021-increase', 'Increase', 'ashby', 'increase'),
  ('seed-0021-column', 'Column', 'ashby', 'column'),
  ('seed-0021-lithic', 'Lithic', 'greenhouse', 'lithic'),
  ('seed-0021-bilt', 'Bilt Rewards', 'greenhouse', 'biltrewards'),
  ('seed-0021-petal', 'Petal', 'greenhouse', 'petal'),
  ('seed-0021-missionlane', 'Mission Lane', 'greenhouse', 'missionlane'),
  ('seed-0021-synctera', 'Synctera', 'greenhouse', 'synctera'),
  ('seed-0021-found', 'Found', 'ashby', 'found'),
  ('seed-0021-hippo', 'Hippo', 'greenhouse', 'hippoinsurance'),
  ('seed-0021-lemonade', 'Lemonade', 'greenhouse', 'lemonade'),
  ('seed-0021-root', 'Root Insurance', 'greenhouse', 'rootinsurance'),
  ('seed-0021-coalition', 'Coalition', 'greenhouse', 'coalitioninc'),
  ('seed-0021-atbay', 'At-Bay', 'greenhouse', 'atbay'),
  ('seed-0021-zed', 'Zed', 'ashby', 'zed'),
  ('seed-0021-continue', 'Continue', 'ashby', 'continue'),
  ('seed-0021-coderabbit', 'CodeRabbit', 'ashby', 'coderabbit'),
  ('seed-0021-greptile', 'Greptile', 'ashby', 'greptile'),
  ('seed-0021-sweep', 'Sweep', 'ashby', 'sweep'),
  ('seed-0021-qodo', 'Qodo (Codium)', 'ashby', 'qodo'),
  ('seed-0021-pulumi', 'Pulumi', 'greenhouse', 'pulumi'),
  ('seed-0021-spacelift', 'Spacelift', 'greenhouse', 'spacelift'),
  ('seed-0021-northflank', 'Northflank', 'ashby', 'northflank'),
  ('seed-0021-koyeb', 'Koyeb', 'ashby', 'koyeb'),
  ('seed-0021-porter', 'Porter', 'ashby', 'porter'),
  ('seed-0021-coherence', 'Coherence', 'ashby', 'coherence'),
  ('seed-0021-tembo', 'Tembo', 'ashby', 'tembo'),
  ('seed-0021-coder', 'Coder', 'greenhouse', 'coder'),
  ('seed-0021-gitpod', 'Gitpod', 'ashby', 'gitpod'),
  ('seed-0021-motherduck', 'MotherDuck', 'ashby', 'motherduck'),
  ('seed-0021-materialize', 'Materialize', 'ashby', 'materialize'),
  ('seed-0021-tinybird', 'Tinybird', 'greenhouse', 'tinybird'),
  ('seed-0021-singlestore', 'SingleStore', 'greenhouse', 'singlestore'),
  ('seed-0021-cockroachlabs', 'Cockroach Labs', 'greenhouse', 'cockroachlabs'),
  ('seed-0021-aiven', 'Aiven', 'greenhouse', 'aiven'),
  ('seed-0021-redpanda', 'Redpanda', 'greenhouse', 'redpandadata'),
  ('seed-0021-tigris', 'Tigris Data', 'ashby', 'tigrisdata'),
  ('seed-0021-restate', 'Restate', 'ashby', 'restate'),
  ('seed-0021-hasura', 'Hasura', 'greenhouse', 'hasura'),
  ('seed-0021-postgresml', 'PostgresML', 'ashby', 'postgresml'),
  ('seed-0021-xata', 'Xata', 'ashby', 'xata'),
  ('seed-0021-highlight', 'Highlight.io', 'ashby', 'highlight'),
  ('seed-0021-betterstack', 'Better Stack', 'ashby', 'betterstack'),
  ('seed-0021-axiom', 'Axiom', 'ashby', 'axiom'),
  ('seed-0021-grafanalabs', 'Grafana Labs', 'greenhouse', 'grafanalabs'),
  ('seed-0021-cribl', 'Cribl', 'greenhouse', 'cribl'),
  ('seed-0021-postmark', 'Postmark', 'greenhouse', 'activecampaign'),
  ('seed-0021-customerio', 'Customer.io', 'greenhouse', 'customerio'),
  ('seed-0021-courier', 'Courier', 'ashby', 'courier'),
  ('seed-0021-workos', 'WorkOS', 'greenhouse', 'workos'),
  ('seed-0021-stytch', 'Stytch', 'greenhouse', 'stytch'),
  ('seed-0021-kinde', 'Kinde', 'ashby', 'kinde'),
  ('seed-0021-bolt', 'Bolt', 'greenhouse', 'bolt'),
  ('seed-0021-cherry', 'Cherry', 'ashby', 'withcherry'),
  ('seed-0021-descript', 'Descript', 'greenhouse', 'descript'),
  ('seed-0021-riverside', 'Riverside', 'greenhouse', 'riversidefm'),
  ('seed-0021-beehiiv', 'Beehiiv', 'ashby', 'beehiiv'),
  ('seed-0021-kit', 'Kit (ConvertKit)', 'greenhouse', 'kit'),
  ('seed-0021-linktree', 'Linktree', 'greenhouse', 'linktree'),
  ('seed-0021-beacons', 'Beacons', 'ashby', 'beacons'),
  ('seed-0021-stan', 'Stan', 'ashby', 'stanstore'),
  ('seed-0021-sigmaos', 'SigmaOS', 'greenhouse', 'sigmaos'),
  ('seed-0021-superhuman', 'Superhuman', 'greenhouse', 'superhuman'),
  ('seed-0021-mem', 'Mem', 'ashby', 'mem'),
  ('seed-0021-amie', 'Amie', 'ashby', 'amie'),
  ('seed-0021-vimcal', 'Vimcal', 'ashby', 'vimcal'),
  ('seed-0021-akiflow', 'Akiflow', 'greenhouse', 'akiflow'),
  ('seed-0021-motion', 'Motion', 'greenhouse', 'usemotion'),
  ('seed-0021-otter', 'Otter.ai', 'greenhouse', 'otter'),
  ('seed-0021-fireflies', 'Fireflies', 'greenhouse', 'firefliesai'),
  ('seed-0021-readai', 'Read.ai', 'ashby', 'readai'),
  ('seed-0021-eightsleep', 'Eight Sleep', 'greenhouse', 'eightsleep'),
  ('seed-0021-oura', 'Oura', 'greenhouse', 'ouraring'),
  ('seed-0021-levels', 'Levels', 'greenhouse', 'levels'),
  ('seed-0021-function', 'Function Health', 'ashby', 'functionhealth'),
  ('seed-0021-strava', 'Strava', 'greenhouse', 'strava'),
  ('seed-0021-peloton', 'Peloton', 'greenhouse', 'peloton'),
  ('seed-0021-causal', 'Causal', 'ashby', 'causal'),
  ('seed-0021-relay', 'Relay', 'ashby', 'relayfi'),
  ('seed-0021-rho', 'Rho', 'greenhouse', 'rho'),
  ('seed-0021-hims', 'Hims & Hers', 'greenhouse', 'forhims'),
  ('seed-0021-ro', 'Ro', 'greenhouse', 'ro'),
  ('seed-0021-stockx', 'StockX', 'greenhouse', 'stockx'),
  ('seed-0021-goat', 'Goat', 'greenhouse', 'goatgroup'),
  ('seed-0021-whatnot', 'Whatnot', 'greenhouse', 'whatnot'),
  ('seed-0021-depop', 'Depop', 'greenhouse', 'depop'),
  ('seed-0021-mercari', 'Mercari', 'greenhouse', 'mercari'),
  ('seed-0021-etsy', 'Etsy', 'greenhouse', 'etsy'),
  ('seed-0021-polymarket', 'Polymarket', 'ashby', 'polymarket'),
  ('seed-0021-hopper', 'Hopper', 'greenhouse', 'hopper'),
  ('seed-0021-going', 'Going', 'greenhouse', 'going'),
  ('seed-0021-toast', 'Toast', 'greenhouse', 'toast'),
  ('seed-0021-opentable', 'OpenTable', 'greenhouse', 'opentable'),
  ('seed-0021-resy', 'Resy', 'greenhouse', 'resy'),
  ('seed-0021-tock', 'Tock', 'greenhouse', 'tock'),
  ('seed-0021-alephalpha', 'Aleph Alpha', 'greenhouse', 'alephalpha'),
  ('seed-0021-helsing', 'Helsing', 'lever', 'helsing'),
  ('seed-0021-preferrednetworks', 'Preferred Networks', 'greenhouse', 'preferrednetworks'),
  ('seed-0021-fiverings', 'Five Rings', 'greenhouse', 'fiverings'),
  ('seed-0021-towerresearch', 'Tower Research Capital', 'greenhouse', 'towerresearchcapital'),
  ('seed-0021-sig', 'Susquehanna (SIG)', 'greenhouse', 'sig'),
  ('seed-0021-akuna', 'Akuna Capital', 'greenhouse', 'akunacapital'),
  ('seed-0021-belvedere', 'Belvedere Trading', 'greenhouse', 'belvederetrading'),
  ('seed-0021-peak6', 'PEAK6', 'greenhouse', 'peak6'),
  ('seed-0021-wolverine', 'Wolverine Trading', 'greenhouse', 'wolverinetrading'),
  ('seed-0021-headlands', 'Headlands Tech', 'greenhouse', 'headlandstech'),
  ('seed-0021-boom', 'Boom Supersonic', 'greenhouse', 'boomsupersonic'),
  ('seed-0021-hermeus', 'Hermeus', 'greenhouse', 'hermeus'),
  ('seed-0021-vast', 'Vast Space', 'greenhouse', 'vast'),
  ('seed-0021-stoke', 'Stoke Space', 'greenhouse', 'stokespace'),
  ('seed-0021-varda', 'Varda Space', 'greenhouse', 'vardaspace'),
  ('seed-0021-k2space', 'K2 Space', 'ashby', 'k2space'),
  ('seed-0021-astranis', 'Astranis', 'greenhouse', 'astranis'),
  ('seed-0021-slingshot', 'Slingshot Aerospace', 'greenhouse', 'slingshotaerospace'),
  ('seed-0021-kairos', 'Kairos Power', 'greenhouse', 'kairospower'),
  ('seed-0021-commonwealth', 'Commonwealth Fusion Systems', 'greenhouse', 'commonwealthfusionsystems'),
  ('seed-0021-helion', 'Helion Energy', 'greenhouse', 'helionenergy'),
  ('seed-0021-tae', 'TAE Technologies', 'greenhouse', 'taetechnologies'),
  ('seed-0021-pacificfusion', 'Pacific Fusion', 'ashby', 'pacificfusion'),
  ('seed-0021-formenergy', 'Form Energy', 'greenhouse', 'formenergy'),
  ('seed-0021-sublime', 'Sublime Systems', 'greenhouse', 'sublimesystems'),
  ('seed-0021-twelve', 'Twelve', 'greenhouse', 'twelve'),
  ('seed-0021-climeworks', 'Climeworks', 'greenhouse', 'climeworks'),
  ('seed-0021-heirloom', 'Heirloom', 'greenhouse', 'heirloomcarbon'),
  ('seed-0021-decart', 'Decart', 'ashby', 'decart'),
  ('seed-0021-wave', 'Wave', 'ashby', 'wavemusic'),
  ('seed-0021-stainless', 'Stainless', 'ashby', 'stainlessapi'),
  ('seed-0021-liblab', 'Liblab', 'ashby', 'liblab'),
  ('seed-0021-speakeasy', 'Speakeasy', 'ashby', 'speakeasyapi'),
  ('seed-0021-wing', 'Wing', 'greenhouse', 'wing'),
  ('seed-0021-zipline', 'Zipline', 'greenhouse', 'flyzipline'),
  ('seed-0021-lamini', 'Lamini', 'ashby', 'lamini');

UPDATE companies
SET ats_type = (
      SELECT seed_0021_companies.ats_type
      FROM seed_0021_companies
      WHERE lower(seed_0021_companies.name) = lower(companies.name)
    ),
    ats_slug = (
      SELECT seed_0021_companies.ats_slug
      FROM seed_0021_companies
      WHERE lower(seed_0021_companies.name) = lower(companies.name)
    ),
    enabled = 1
WHERE EXISTS (
  SELECT 1
  FROM seed_0021_companies
  WHERE lower(seed_0021_companies.name) = lower(companies.name)
);

INSERT INTO companies (id, name, ats_type, ats_slug, website, enabled, added_at)
SELECT id, name, ats_type, ats_slug, '', 1, datetime('now')
FROM seed_0021_companies
WHERE NOT EXISTS (
  SELECT 1
  FROM companies
  WHERE lower(companies.name) = lower(seed_0021_companies.name)
);

DROP TABLE seed_0021_companies;
