// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "chevron": string;
  readonly "copy": string;
  readonly "groups": string;
  readonly "row": string;
  readonly "select": string;
};

export default styles;
