// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "chips": string;
  readonly "editor": string;
  readonly "item": string;
  readonly "pair": string;
  readonly "row": string;
  readonly "rowMain": string;
};

export default styles;
