// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "content": string;
  readonly "retry": string;
  readonly "root": string;
};

export default styles;
