// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "chevron": string;
  readonly "chips": string;
  readonly "group": string;
  readonly "hidden": string;
  readonly "pair": string;
  readonly "removable": string;
  readonly "review": string;
  readonly "row": string;
  readonly "rowCopy": string;
  readonly "switchRow": string;
  readonly "viewActions": string;
};

export default styles;
