// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "action": string;
  readonly "close": string;
  readonly "icon": string;
  readonly "message": string;
  readonly "toast": string;
  readonly "viewport": string;
};

export default styles;
