// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "chip": string;
  readonly "item": string;
  readonly "root": string;
  readonly "segment": string;
};

export default styles;
