// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "actions": string;
  readonly "call": string;
  readonly "calls": string;
  readonly "detail": string;
  readonly "empty": string;
  readonly "entry": string;
  readonly "entryCopy": string;
  readonly "entryHead": string;
  readonly "issue": string;
  readonly "item": string;
  readonly "link": string;
  readonly "links": string;
  readonly "log": string;
  readonly "metric": string;
  readonly "metricList": string;
  readonly "metrics": string;
  readonly "reasons": string;
  readonly "runTitle": string;
  readonly "sectionHead": string;
  readonly "status": string;
  readonly "table": string;
  readonly "tags": string;
  readonly "textButton": string;
};

export default styles;
