/**
 * Generates the web stylesheet, native token values and kit prop unions from
 * `src/tokens.ts`. Run `bun run generate` after changing the source, or
 * `bun run generate --check` to verify the committed files are current.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { oklchToNative } from "../src/oklch";
import {
  base,
  breakpoints,
  colorScheme,
  contrast,
  contrastLight,
  dark,
  groups,
  light,
  reducedMotion,
  singleGroups,
  wide,
} from "../src/tokens";

const packageRoot = join(import.meta.dir, "..");
const REM_BASE = 16;

type TokenMap = Record<string, string>;
type NativeValue = string | number | NativeValue[] | { [key: string]: NativeValue };

const modes = {
  dark: { ...base, ...dark },
  light: { ...base, ...dark, ...light },
  contrast: { ...base, ...dark, ...contrast },
  lightContrast: { ...base, ...dark, ...light, ...contrastLight },
} as const satisfies Record<string, TokenMap>;

const modeNames = Object.keys(modes) as (keyof typeof modes)[];

// ---------------------------------------------------------------------------
// Web stylesheet

function declarations(map: TokenMap, indent: string): string {
  return Object.entries(map)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join("\n");
}

function rule(selector: string, map: TokenMap, indent = "  "): string {
  return [
    `${indent}${selector} {`,
    declarations(map, `${indent}  `),
    `${indent}}`,
  ].join("\n");
}

export function renderCss(): string {
  return `/*
 * Generated by scripts/generate.ts from src/tokens.ts. Do not edit by hand.
 * Values mirror the frozen Svelte design until chunk 3.4 deletes it; the
 * equivalence check compares every resolved value against that copy.
 */
@layer reset, tokens, base, kit, app;

@layer tokens {
${rule(":root", { "color-scheme": colorScheme.dark, ...base, ...dark })}

  @media (min-width: ${breakpoints.wide}px) {
${rule(":root", wide, "    ")}
  }

${rule('[data-mode="light"]', { "color-scheme": colorScheme.light, ...light })}

  /* WKWebView does not consistently expose iOS Increase Contrast through the
     media query, so the native bridge mirrors it as a data attribute too. */
${rule(':root[data-ios-contrast="more"]', contrast)}

${rule(':root[data-mode="light"][data-ios-contrast="more"]', contrastLight)}

  @media (prefers-contrast: more) {
${rule(":root", contrast, "    ")}

${rule(':root[data-mode="light"]', contrastLight, "    ")}
  }

  @media (prefers-reduced-motion: reduce) {
${rule(":root", reducedMotion, "    ")}
  }
}
`;
}

// ---------------------------------------------------------------------------
// Native values

/** Replaces `var(--x)` references so native gets final values, not aliases. */
function resolveVars(map: TokenMap, value: string, seen: string[] = []): string {
  return value.replace(/var\((--[\w-]+)(?:\s*,\s*([^()]*))?\)/g, (_match, name: string, fallback?: string) => {
    const raw = map[name];
    if (raw === undefined) {
      if (fallback !== undefined) return fallback.trim();
      throw new Error(`Unresolved variable ${name} while generating native tokens`);
    }
    if (seen.includes(name)) throw new Error(`Circular variable reference: ${[...seen, name].join(" -> ")}`);
    return resolveVars(map, raw, [...seen, name]);
  });
}

/** Web-only values (safe areas, calc() compositions) have no native number. */
const isWebOnly = (value: string) => /env\(|calc\(/.test(value);

function toNumber(value: string): number {
  const trimmed = value.trim();
  const minimum = /^min\((.+)\)$/.exec(trimmed);
  if (minimum) return Math.min(...minimum[1].split(",").map((part) => toNumber(part)));
  const px = /^(-?[\d.]+)px$/.exec(trimmed);
  if (px) return round(Number(px[1]));
  const rem = /^(-?[\d.]+)rem$/.exec(trimmed);
  if (rem) return round(Number(rem[1]) * REM_BASE);
  const em = /^(-?[\d.]+)em$/.exec(trimmed);
  if (em) return round(Number(em[1]));
  const ms = /^(-?[\d.]+)ms$/.exec(trimmed);
  if (ms) return round(Number(ms[1]));
  if (/^-?[\d.]+$/.test(trimmed)) return round(Number(trimmed));
  throw new Error(`Cannot convert ${value} to a native number`);
}

const round = (value: number) => Math.round(value * 1000) / 1000;

function toEasing(value: string): number[] {
  const match = /^cubic-bezier\((.+)\)$/.exec(value.trim());
  if (!match) throw new Error(`Cannot convert ${value} to a native easing`);
  return match[1].split(",").map((part) => Number(part.trim()));
}

function toShadow(value: string): NativeValue {
  const match = /^(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(.+)$/.exec(value.trim());
  if (!match) throw new Error(`Cannot convert ${value} to a native shadow`);
  return {
    x: Number(match[1]),
    y: Number(match[2]),
    blur: Number(match[3]),
    color: oklchToNative(match[4]),
  };
}

function convertValue(value: string, kind: "number" | "color" | "shadow" | "easing" | "string"): NativeValue | undefined {
  if (isWebOnly(value)) return undefined;
  if (kind === "number") return toNumber(value);
  if (kind === "color") return oklchToNative(value);
  if (kind === "shadow") return toShadow(value);
  if (kind === "easing") return toEasing(value);
  return value;
}

function groupValues(map: TokenMap, prefix: string, kind: Parameters<typeof convertValue>[1]): Record<string, NativeValue> {
  const values: Record<string, NativeValue> = {};
  for (const [name, value] of Object.entries(map)) {
    if (!name.startsWith(prefix)) continue;
    const converted = convertValue(resolveVars(map, value), kind);
    if (converted !== undefined) values[name.slice(prefix.length)] = converted;
  }
  return values;
}

function groupValuesFromNames(map: TokenMap, names: readonly string[], kind: Parameters<typeof convertValue>[1]): Record<string, NativeValue> {
  const values: Record<string, NativeValue> = {};
  for (const name of names) {
    const value = map[name];
    if (value === undefined) throw new Error(`Missing token ${name} while generating native values`);
    const converted = convertValue(resolveVars(map, value), kind);
    if (converted !== undefined) values[name.replace(/^--/, "")] = converted;
  }
  return values;
}

const SCALAR_GROUPS = [
  ["radius", "number"],
  ["space", "number"],
  ["fontSize", "number"],
  ["fontFamily", "string"],
  ["leading", "number"],
  ["tracking", "number"],
  ["duration", "number"],
  ["ease", "easing"],
  ["zIndex", "number"],
] as const;

function renderNative(): string {
  const sections: string[] = [];
  sections.push(`export const breakpoints = ${tsValue(breakpoints)} as const;`);
  sections.push([
    `export const color = {`,
    ...modeNames.map((mode) => `${indent(2)}${tsKey(mode)}: ${tsValue(groupValues(modes[mode], "--color-", "color"), 2)},`),
    `} satisfies Record<ThemeName, Record<ColorToken, string>>;`,
  ].join("\n"));
  sections.push([
    `export interface NativeShadow {`,
    `${indent(1)}x: number;`,
    `${indent(1)}y: number;`,
    `${indent(1)}blur: number;`,
    `${indent(1)}color: string;`,
    `}`,
    ``,
    `export const shadow = {`,
    ...modeNames.map((mode) => `${indent(2)}${tsKey(mode)}: ${tsValue(groupValues(modes[mode], "--shadow-", "shadow"), 2)},`),
    `} satisfies Record<ThemeName, Record<ShadowToken, NativeShadow>>;`,
  ].join("\n"));

  const scalars = { ...base, ...dark };
  for (const [group, kind] of SCALAR_GROUPS) {
    const prefix = groups[group].prefix;
    sections.push(`export const ${group} = ${tsValue(groupValues(scalars, prefix, kind))} as const;`);
  }
  for (const [group, names] of Object.entries(singleGroups)) {
    const values = groupValuesFromNames(scalars, names, "number");
    if (Object.keys(values).length === 0) continue;
    sections.push(`export const ${group} = ${tsValue(values)} as const;`);
  }

  return `/**
 * Generated by scripts/generate.ts from src/tokens.ts. Do not edit by hand.
 *
 * Colors convert to hex/rgba and lengths to point numbers at the 16px web root.
 * Safe-area and calc() compositions are web-only and intentionally absent;
 * native supplies safe areas through the platform. Modes mirror the web
 * cascade: \`light\`, \`contrast\` and \`lightContrast\` override \`dark\`.
 * The native kit (6.2) may reshape this data, but token names stay aligned
 * with the web kit's prop values.
 */
import type { ColorToken, ShadowToken, ThemeName } from "./types";

${sections.join("\n\n")}
`;
}

// ---------------------------------------------------------------------------
// Kit prop unions

const tokenName = (key: string) => `${key[0].toUpperCase()}${key.slice(1)}Token`;

function renderTypes(): string {
  const sections = [
    `export type ThemeName = ${union(modeNames)};`,
    `export type BreakpointToken = ${union(Object.keys(breakpoints))};`,
  ];
  for (const [group, definition] of Object.entries(groups)) {
    const source = "modes" in definition && definition.modes ? dark : { ...base, ...dark };
    const keys = Object.keys(source)
      .filter((name) => name.startsWith(definition.prefix))
      .map((name) => name.slice(definition.prefix.length));
    if (keys.length === 0) throw new Error(`Token group ${group} has no values for prefix ${definition.prefix}`);
    sections.push(`export type ${tokenName(group)} = ${union(keys)};`);
  }
  return `/**
 * Generated by scripts/generate.ts from src/tokens.ts. Do not edit by hand.
 *
 * Prop-value unions shared by the web and native kits, so an off-scale value
 * is a type error on both platforms.
 */
${sections.join("\n")}
`;
}

function union(values: readonly string[]): string {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

// ---------------------------------------------------------------------------
// Serialization

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const tsKey = (key: string) => (IDENTIFIER.test(key) ? key : JSON.stringify(key));
const indent = (depth: number) => "  ".repeat(depth);

function tsValue(value: NativeValue, depth = 0): string {
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map((item) => tsValue(item)).join(", ")}]`;
  const entries = Object.entries(value);
  if (entries.length === 0) return "{}";
  return [
    `{`,
    ...entries.map(([key, item]) => `${indent(depth + 1)}${tsKey(key)}: ${tsValue(item, depth + 1)},`),
    `${indent(depth)}}`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Entry point

export const outputs = {
  "src/tokens.css": renderCss,
  "src/native.ts": renderNative,
  "src/types.ts": renderTypes,
} as const;

export function checkOutputs(): string[] {
  const drifted: string[] = [];
  for (const [path, render] of Object.entries(outputs)) {
    const existing = existsSync(join(packageRoot, path)) ? readFileSync(join(packageRoot, path), "utf8") : null;
    if (existing !== render()) drifted.push(path);
  }
  return drifted;
}

export function writeOutputs(): void {
  for (const [path, render] of Object.entries(outputs)) {
    writeFileSync(join(packageRoot, path), render());
  }
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const drifted = checkOutputs();
    if (drifted.length > 0) {
      console.error(`Generated token files are out of date:\n  ${drifted.join("\n  ")}\nRun: bun --filter @pinkslip/tokens generate`);
      process.exit(1);
    }
    console.log("Generated token files are up to date.");
  } else {
    writeOutputs();
    console.log("Generated src/tokens.css, src/native.ts and src/types.ts.");
  }
}
