// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "accessory": string;
  readonly "body": string;
  readonly "company": string;
  readonly "dot": string;
  readonly "link": string;
  readonly "location": string;
  readonly "meta": string;
  readonly "new": string;
  readonly "reason": string;
  readonly "root": string;
  readonly "salary": string;
  readonly "sub": string;
  readonly "time": string;
  readonly "title": string;
};

export default styles;
