// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "infoTrigger": string;
  readonly "popup": string;
  readonly "positioner": string;
  readonly "title": string;
};

export default styles;
