/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WebBindings` (hash: 15da60507067ec84e3f2ef62074b34d9)
interface __BaseEnv_WebBindings {
	API: Fetcher /* pinkslip */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_WebBindings {}
}
interface WebBindings extends __BaseEnv_WebBindings {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}