/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WebBindings` (hash: 473eb29c81dcbd8ad8915bd7c6b11d25)
interface __BaseEnv_WebBindings {
	SEARCH_INDEXING: "on";
	API: Fetcher /* pinkslip */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_WebBindings {}
}
interface WebBindings extends __BaseEnv_WebBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEARCH_INDEXING">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}