// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "end": string;
  readonly "intro": string;
  readonly "list": string;
  readonly "more": string;
  readonly "root": string;
  readonly "salary": string;
  readonly "sheetActions": string;
  readonly "skeletonCopy": string;
  readonly "skeletonRow": string;
  readonly "toggleRow": string;
  readonly "toolbar": string;
};

export default styles;
