// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "box": string;
  readonly "check": string;
  readonly "check-in": string;
  readonly "label": string;
};

export default styles;
