// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "back": string;
  readonly "body": string;
  readonly "done": string;
  readonly "footer": string;
  readonly "header": string;
  readonly "headerRow": string;
  readonly "root": string;
  readonly "step": string;
  readonly "step-in": string;
  readonly "title": string;
};

export default styles;
