/**
 * Generates a `*.module.css.d.ts` beside every CSS module so `tsc` checks
 * class names instead of accepting any string. `--check` verifies the committed
 * declarations are current; orphan declarations are reported too.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const sourceRoot = resolve(repoRoot, "apps/webapp/src");

/** Local class names plus keyframes names, never `:global(...)`, URLs or decimals. */
export function extractClassNames(css: string): string[] {
  const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const source = stripBlocks(stripBlocks(withoutComments, ":global("), "url(");
  const names = new Set<string>();
  for (const match of source.matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)) names.add(match[1]);
  for (const match of source.matchAll(/@keyframes\s+([_a-zA-Z][\w-]*)/g)) names.add(match[1]);
  return [...names].sort();
}

function stripBlocks(source: string, opener: string): string {
  let result = "";
  let index = 0;
  while (index < source.length) {
    const start = source.indexOf(opener, index);
    if (start < 0) return result + source.slice(index);
    result += source.slice(index, start);
    let depth = 1;
    let cursor = start + opener.length;
    while (cursor < source.length && depth > 0) {
      if (source[cursor] === "(") depth++;
      else if (source[cursor] === ")") depth--;
      cursor++;
    }
    index = cursor;
  }
  return result;
}

export function renderDeclaration(classes: readonly string[]): string {
  return [
    "// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.",
    "declare const styles: {",
    ...classes.map((name) => `  readonly ${JSON.stringify(name)}: string;`),
    "};",
    "",
    "export default styles;",
    "",
  ].join("\n");
}

interface FoundModules {
  css: string[];
  declarations: string[];
}

function findModules(dir: string): FoundModules {
  const found: FoundModules = { css: [], declarations: [] };
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      const nested = findModules(path);
      found.css.push(...nested.css);
      found.declarations.push(...nested.declarations);
    } else if (entry.name.endsWith(".module.css.d.ts")) {
      found.declarations.push(path);
    } else if (entry.name.endsWith(".module.css")) {
      found.css.push(path);
    }
  }
  return found;
}

export function checkDeclarations(): string[] {
  const drifted: string[] = [];
  const found = findModules(sourceRoot);
  for (const path of found.css.sort()) {
    const declaration = renderDeclaration(extractClassNames(readFileSync(path, "utf8")));
    const target = `${path}.d.ts`;
    if (!existsSync(target) || readFileSync(target, "utf8") !== declaration) {
      drifted.push(relative(repoRoot, target));
    }
  }
  for (const path of found.declarations.sort()) {
    if (!existsSync(path.slice(0, -".d.ts".length))) {
      drifted.push(`${relative(repoRoot, path)} has no matching CSS module`);
    }
  }
  return drifted;
}

export function writeDeclarations(): void {
  for (const path of findModules(sourceRoot).css.sort()) {
    writeFileSync(`${path}.d.ts`, renderDeclaration(extractClassNames(readFileSync(path, "utf8"))));
  }
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const drifted = checkDeclarations();
    if (drifted.length > 0) {
      console.error(`CSS module declarations are out of date:\n  ${drifted.join("\n  ")}\nRun: bun --filter @pinkslip/webapp generate:css-modules`);
      process.exit(1);
    }
    console.log("CSS module declarations are up to date.");
  } else {
    writeDeclarations();
    console.log("Wrote CSS module declarations.");
  }
}
