// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "actions": string;
  readonly "icon": string;
  readonly "message": string;
  readonly "root": string;
};

export default styles;
