/* Generated by scripts/export-native-tokens.ts from packages/ui/src/styles/theme.css
   and skin.css. Do not edit by hand: change the CSS and run the script. */

export const light = {
  "bg": "#fbfaf9",
  "raised": "#ffffff",
  "sunken": "#f3f2f0",
  "field": "#ffffff",
  "control": "#eeedea",
  "controlHover": "#e4e3e0",
  "ink": "#111114",
  "ink2": "#37383b",
  "ink3": "#5a5a5e",
  "line": "#e1dfdd",
  "line2": "#c7c5c3",
  "inverse": "#1c1d20",
  "inverseInk": "#f9f8f7",
  "accent": "#be296a",
  "accentHover": "#b0175f",
  "accentInk": "#fdfbfa",
  "accentText": "#be296a",
  "accentEdge": "#8a1150",
  "accentSoft": "#feedf2",
  "accentSoftInk": "#85204a",
  "good": "#007132",
  "goodSoft": "#e5f5e7",
  "warn": "#916102",
  "warnSoft": "#fbf1dc",
  "bad": "#b32228",
  "badSoft": "#ffebe9",
  "badInk": "#fdfbfa",
  "scrim": "rgba(5, 6, 8, 0.38)",
  "thumb": "#ffffff",
  "skinHi": "rgba(255, 255, 255, 0.55)",
  "skinHiStrong": "rgba(255, 255, 255, 0.75)",
  "skinShadeSm": "rgba(13, 13, 17, 0.06)",
  "skinShade": "rgba(13, 13, 17, 0.14)",
  "skinInset": "rgba(13, 13, 17, 0.09)",
  "skinTop": "#ffffff",
  "skinBottom": "#f1f0ed",
  "skinThumbBottom": "#f1f0ee",
  "accentTop": "#c83f6b",
  "accentBottom": "#b6186b",
  "edgeTop": "#dcdad8",
  "edgeBottom": "#b0adaa",
  "accentEdgeTop": "#ae446b"
} as const;

export const dark: Record<keyof typeof light, string> = {
  "bg": "#0e0e10",
  "raised": "#17171a",
  "sunken": "#08080a",
  "field": "#131316",
  "control": "#202023",
  "controlHover": "#2a2a2e",
  "ink": "#f3f3f5",
  "ink2": "#c3c4c7",
  "ink3": "#98989c",
  "line": "#2a2a2d",
  "line2": "#3e3e42",
  "inverse": "#ebebed",
  "inverseInk": "#111114",
  "accent": "#cd3976",
  "accentHover": "#db4781",
  "accentInk": "#fdfbfa",
  "accentText": "#fa7ba7",
  "accentEdge": "#8d0350",
  "accentSoft": "#3c1221",
  "accentSoftInk": "#ffb3ce",
  "good": "#5ec077",
  "goodSoft": "#112315",
  "warn": "#efac44",
  "warnSoft": "#2d1f0a",
  "bad": "#fd736d",
  "badSoft": "#331715",
  "badInk": "#110c0b",
  "scrim": "rgba(0, 0, 0, 0.52)",
  "thumb": "#f1f1f4",
  "skinHi": "rgba(255, 255, 255, 0.1)",
  "skinHiStrong": "rgba(255, 255, 255, 0.22)",
  "skinShadeSm": "rgba(0, 0, 0, 0.25)",
  "skinShade": "rgba(0, 0, 0, 0.45)",
  "skinInset": "rgba(0, 0, 0, 0.35)",
  "skinTop": "#2d2d31",
  "skinBottom": "#222226",
  "skinThumbBottom": "#d7d7d9",
  "accentTop": "#d64c76",
  "accentBottom": "#c42b77",
  "edgeTop": "#444549",
  "edgeBottom": "#18181b",
  "accentEdgeTop": "#b1406b"
};

export const text = {
  "caption": {
    "size": 12,
    "lineHeight": 16
  },
  "meta": {
    "size": 13,
    "lineHeight": 18
  },
  "ui": {
    "size": 14,
    "lineHeight": 20
  },
  "body": {
    "size": 16,
    "lineHeight": 24
  },
  "lead": {
    "size": 18,
    "lineHeight": 26
  },
  "title": {
    "size": 21,
    "lineHeight": 26
  },
  "heading": {
    "size": 24,
    "lineHeight": 28
  },
  "display": {
    "size": 32,
    "lineHeight": 36
  },
  "hero": {
    "size": 40,
    "lineHeight": 42
  }
} as const;

export const radius = {
  "mark": 5,
  "item": 6,
  "inset": 6,
  "control": 8,
  "surface": 12,
  "sheet": 16,
  "pill": 999
} as const;

/** Control heights: small, medium, large. Type size follows height. */
export const control = { sm: 28, md: 36, lg: 44 } as const;

/** Durations in milliseconds. */
export const duration = {
  "instant": 90,
  "fast": 150,
  "base": 200,
  "slow": 280,
  "exit": 120,
  "sheet": 440,
  "sheetExit": 260
} as const;
