// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "actions": string;
  readonly "copy": string;
  readonly "row": string;
  readonly "status": string;
  readonly "titleRow": string;
};

export default styles;
