// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "checkItem": string;
  readonly "chevron": string;
  readonly "fieldTrigger": string;
  readonly "fieldValue": string;
  readonly "item": string;
  readonly "popup": string;
  readonly "positioner": string;
  readonly "separator": string;
};

export default styles;
