// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "brand": string;
  readonly "brandPink": string;
  readonly "destination": string;
  readonly "destinations": string;
  readonly "frame": string;
  readonly "legal": string;
  readonly "main": string;
  readonly "mark": string;
  readonly "navigation": string;
  readonly "skip": string;
};

export default styles;
