// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "brand": string;
  readonly "content": string;
  readonly "destination": string;
  readonly "destinations": string;
  readonly "frame": string;
  readonly "legal": string;
  readonly "main": string;
  readonly "mark": string;
  readonly "navigation": string;
  readonly "phoneSections": string;
  readonly "screenNav": string;
  readonly "screenTitle": string;
  readonly "sectionGroup": string;
  readonly "sectionLink": string;
  readonly "sections": string;
  readonly "sidebarSections": string;
  readonly "skip": string;
};

export default styles;
