// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "composerActions": string;
  readonly "done": string;
  readonly "dot": string;
  readonly "loading": string;
  readonly "secondary": string;
  readonly "step": string;
  readonly "steps": string;
  readonly "textButton": string;
};

export default styles;
