// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "body": string;
  readonly "caret": string;
  readonly "panel": string;
  readonly "root": string;
  readonly "trigger": string;
};

export default styles;
