// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "company": string;
  readonly "intro": string;
  readonly "job": string;
  readonly "list": string;
  readonly "meta": string;
  readonly "title": string;
};

export default styles;
