// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "bleed": string;
  readonly "control": string;
  readonly "narrow": string;
  readonly "row": string;
};

export default styles;
