// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "body": string;
  readonly "eyebrow": string;
  readonly "header": string;
  readonly "page": string;
  readonly "subtitle": string;
  readonly "title": string;
};

export default styles;
