// Generated by scripts/generate-webapp-css-modules.ts. Do not edit.
declare const styles: {
  readonly "brand": string;
  readonly "footer": string;
  readonly "header": string;
  readonly "navigation": string;
  readonly "shell": string;
  readonly "skip": string;
};

export default styles;
