interface TailoredResumeTexOptions {
  companyName?: string | null;
  jobTitle?: string | null;
  sourceTex?: string | null;
}

type ResumeLine =
  | { kind: "heading"; text: string }
  | { kind: "bullet"; text: string }
  | { kind: "text"; text: string }
  | { kind: "blank" };

const DEFAULT_PREAMBLE = String.raw`% Generated by Pinkslip
\documentclass[letterpaper,11pt]{article}

\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage[usenames,dvipsnames]{color}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage[english]{babel}
\usepackage{tabularx}

\pagestyle{empty}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]
\setlist[itemize]{leftmargin=0.18in, itemsep=1pt, topsep=2pt, parsep=0pt, partopsep=0pt}
`;

function stripMarkdownInline(input: string) {
  return input
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .trim();
}

function escapeLatex(input: string) {
  return stripMarkdownInline(input).replace(/[\\&%$#_{}~^]/g, (char) => {
    switch (char) {
      case "\\":
        return String.raw`\textbackslash{}`;
      case "&":
        return String.raw`\&`;
      case "%":
        return String.raw`\%`;
      case "$":
        return String.raw`\$`;
      case "#":
        return String.raw`\#`;
      case "_":
        return String.raw`\_`;
      case "{":
        return String.raw`\{`;
      case "}":
        return String.raw`\}`;
      case "~":
        return String.raw`\textasciitilde{}`;
      case "^":
        return String.raw`\textasciicircum{}`;
      default:
        return char;
    }
  });
}

function headingFromLine(line: string) {
  const markdownHeading = line.match(/^#{1,4}\s+(.+)$/);
  if (markdownHeading) return stripMarkdownInline(markdownHeading[1]).replace(/:$/, "");

  const noColon = stripMarkdownInline(line).replace(/:$/, "");
  if (noColon.length > 2 && noColon.length < 64 && /^[A-Z][A-Z0-9/&., +'-]+$/.test(noColon)) {
    return noColon;
  }

  return null;
}

function parseResumeLines(markdown: string): ResumeLine[] {
  return markdown
    .replace(/\r/g, "")
    .split("\n")
    .map((rawLine) => {
      const line = rawLine.trim();
      if (!line) return { kind: "blank" };

      const heading = headingFromLine(line);
      if (heading) return { kind: "heading", text: heading };

      const bullet = line.match(/^[-*\u2022]\s+(.+)$/);
      if (bullet) return { kind: "bullet", text: bullet[1].trim() };

      return { kind: "text", text: line };
    });
}

function renderTextLine(text: string) {
  const escaped = escapeLatex(text);
  if (text.includes("|") || / -- | - /.test(text)) {
    return String.raw`\textbf{${escaped}}\\[-1pt]`;
  }
  return String.raw`${escaped}\\[-1pt]`;
}

function renderResumeBody(markdown: string) {
  const lines = parseResumeLines(markdown);
  const output: string[] = [];
  let inItems = false;
  let seenHeading = false;
  let headerLines: string[] = [];

  const closeItems = () => {
    if (!inItems) return;
    output.push(String.raw`\end{itemize}`);
    inItems = false;
  };

  const flushHeader = () => {
    if (seenHeading || headerLines.length === 0) return;
    const [name, ...contact] = headerLines;
    output.push(String.raw`\begin{center}`);
    output.push(String.raw`  \textbf{\huge \scshape ${escapeLatex(name)}}`);
    if (contact.length > 0) {
      output.push(String.raw`  \\ \vspace{2pt}`);
      output.push(String.raw`  ${escapeLatex(contact.join(" | "))}`);
    }
    output.push(String.raw`\end{center}`);
    output.push(String.raw`\vspace{-12pt}`);
    headerLines = [];
  };

  for (const line of lines) {
    if (line.kind === "blank") {
      closeItems();
      if (!seenHeading) flushHeader();
      continue;
    }

    if (line.kind === "heading") {
      closeItems();
      flushHeader();
      seenHeading = true;
      output.push("");
      output.push(String.raw`\section{${escapeLatex(line.text)}}`);
      continue;
    }

    if (!seenHeading && line.kind === "text") {
      headerLines.push(line.text);
      continue;
    }

    flushHeader();

    if (line.kind === "bullet") {
      if (!inItems) {
        output.push(String.raw`\begin{itemize}`);
        inItems = true;
      }
      output.push(String.raw`  \item ${escapeLatex(line.text)}`);
      continue;
    }

    closeItems();
    output.push(renderTextLine(line.text));
  }

  closeItems();
  flushHeader();

  return output.join("\n").trim();
}

function replaceDocumentBody(sourceTex: string, body: string) {
  const begin = sourceTex.indexOf(String.raw`\begin{document}`);
  const end = sourceTex.lastIndexOf(String.raw`\end{document}`);
  if (begin === -1 || end === -1 || end <= begin) return null;

  const beforeDocument = sourceTex.slice(0, begin);
  return `${beforeDocument}${String.raw`\begin{document}`}\n\n${body}\n\n${String.raw`\end{document}`}\n`;
}

export function buildTailoredResumeTex(markdown: string, options: TailoredResumeTexOptions = {}) {
  const body = renderResumeBody(markdown);
  const sourceBased = options.sourceTex ? replaceDocumentBody(options.sourceTex, body) : null;
  if (sourceBased) {
    return `% Tailored for ${options.companyName ?? "job"} - ${options.jobTitle ?? "role"}\n${sourceBased}`;
  }

  return `% Tailored for ${options.companyName ?? "job"} - ${options.jobTitle ?? "role"}\n${DEFAULT_PREAMBLE}\n\\begin{document}\n\n${body}\n\n\\end{document}\n`;
}

function slugify(input: string) {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

export function tailoredResumeTexFileName(companyName?: string | null, jobTitle?: string | null) {
  const slug = slugify([companyName, jobTitle, "resume"].filter(Boolean).join(" "));
  return `${slug || "tailored-resume"}.tex`;
}

export function downloadTextFile(fileName: string, text: string, mimeType = "text/plain;charset=utf-8") {
  if (typeof document === "undefined") return;
  const blob = new Blob([text], { type: mimeType });
  const url = URL.createObjectURL(blob);
  try {
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = fileName;
    anchor.rel = "noopener";
    anchor.click();
  } finally {
    window.setTimeout(() => URL.revokeObjectURL(url), 120_000);
  }
}
