interface TailoredResumeTexOptions {
  companyName?: string | null;
  jobTitle?: string | null;
  sourceTex?: string | null;
}

interface RenderResumeBodyOptions {
  sourceHeaderTex?: string | null;
  useResumeItemMacros?: boolean;
}

type ResumeLine =
  | { kind: "heading"; text: string }
  | { kind: "bullet"; text: string }
  | { kind: "text"; text: string }
  | { kind: "blank" };

interface MarkdownBullet {
  section: string;
  text: string;
}

const STOP_WORDS = new Set([
  "the",
  "and",
  "for",
  "with",
  "from",
  "that",
  "this",
  "into",
  "using",
  "used",
  "via",
  "by",
  "to",
  "of",
  "in",
  "on",
  "a",
  "an",
  "as",
  "at",
  "or",
  "is",
  "are",
  "be",
  "was",
  "were",
]);

const SHORT_TECH_TOKENS = new Set(["ai", "ml", "ui", "ux", "js", "go", "c"]);

const DEFAULT_PREAMBLE = String.raw`% Generated by Pinkslip
\documentclass[letterpaper,11pt]{article}

\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage[usenames,dvipsnames]{color}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage[english]{babel}
\usepackage{tabularx}

\pagestyle{empty}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]
\setlist[itemize]{leftmargin=0.18in, itemsep=1pt, topsep=2pt, parsep=0pt, partopsep=0pt}
`;

function stripMarkdownInline(input: string) {
  return input
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .trim();
}

function escapeLatex(input: string) {
  return stripMarkdownInline(input).replace(/[\\&%$#_{}~^]/g, (char) => {
    switch (char) {
      case "\\":
        return String.raw`\textbackslash{}`;
      case "&":
        return String.raw`\&`;
      case "%":
        return String.raw`\%`;
      case "$":
        return String.raw`\$`;
      case "#":
        return String.raw`\#`;
      case "_":
        return String.raw`\_`;
      case "{":
        return String.raw`\{`;
      case "}":
        return String.raw`\}`;
      case "~":
        return String.raw`\textasciitilde{}`;
      case "^":
        return String.raw`\textasciicircum{}`;
      default:
        return char;
    }
  });
}

function headingFromLine(line: string) {
  const markdownHeading = line.match(/^#{1,4}\s+(.+)$/);
  if (markdownHeading) return stripMarkdownInline(markdownHeading[1]).replace(/:$/, "");

  const noColon = stripMarkdownInline(line).replace(/:$/, "");
  if (noColon.length > 2 && noColon.length < 64 && /^[A-Z][A-Z0-9/&., +'-]+$/.test(noColon)) {
    return noColon;
  }

  return null;
}

function parseResumeLines(markdown: string): ResumeLine[] {
  return markdown
    .replace(/\r/g, "")
    .split("\n")
    .map((rawLine) => {
      const line = rawLine.trim();
      if (!line) return { kind: "blank" };

      const heading = headingFromLine(line);
      if (heading) return { kind: "heading", text: heading };

      const bullet = line.match(/^[-*\u2022]\s+(.+)$/);
      if (bullet) return { kind: "bullet", text: bullet[1].trim() };

      return { kind: "text", text: line };
    });
}

function normalizeSectionName(input: string) {
  const normalized = stripMarkdownInline(input)
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

  if (/work|experience|employment/.test(normalized)) return "experience";
  if (/project/.test(normalized)) return "projects";
  if (/education/.test(normalized)) return "education";
  if (/skill|technolog|language|certification/.test(normalized)) return "skills";
  if (/leadership|affiliation|honor|award/.test(normalized)) return "leadership";
  return normalized || "resume";
}

function parseMarkdownBullets(markdown: string): MarkdownBullet[] {
  let currentSection = "resume";
  const bullets: MarkdownBullet[] = [];

  for (const line of parseResumeLines(markdown)) {
    if (line.kind === "heading") {
      currentSection = normalizeSectionName(line.text);
      continue;
    }
    if (line.kind === "bullet") {
      bullets.push({
        section: currentSection,
        text: stripMarkdownInline(line.text),
      });
    }
  }

  return bullets;
}

function latexToPlain(input: string) {
  let output = input;
  for (let pass = 0; pass < 4; pass += 1) {
    output = output
      .replace(/\\href\{([^{}]*)\}\{([^{}]*)\}/g, "$2 ($1)")
      .replace(/\\(?:textbf|textit|emph|underline|small|large|scshape)\{([^{}]*)\}/g, "$1");
  }

  return output
    .replace(/\\&/g, "&")
    .replace(/\\%/g, "%")
    .replace(/\\#/g, "#")
    .replace(/\\_/g, "_")
    .replace(/\\[a-zA-Z@]+(\[[^\]]*\])?/g, " ")
    .replace(/[{}]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tokensForSimilarity(input: string) {
  const normalized = input
    .toLowerCase()
    .replace(/c\+\+/g, "cpp")
    .replace(/c#/g, "csharp")
    .replace(/node\.js/g, "nodejs")
    .replace(/[^a-z0-9+#.]+/g, " ");

  const tokens = normalized
    .split(/\s+/)
    .map((token) => token.trim())
    .filter((token) => {
      if (!token) return false;
      if (STOP_WORDS.has(token)) return false;
      return token.length > 2 || SHORT_TECH_TOKENS.has(token);
    });

  return new Set(tokens);
}

function overlapScore(source: string, candidate: string) {
  const sourceTokens = tokensForSimilarity(source);
  const candidateTokens = tokensForSimilarity(candidate);
  if (sourceTokens.size === 0 || candidateTokens.size === 0) return 0;

  let overlap = 0;
  for (const token of candidateTokens) {
    if (sourceTokens.has(token)) overlap += 1;
  }

  return overlap / Math.min(sourceTokens.size, candidateTokens.size);
}

function candidateLooksSafe(candidate: string) {
  if (/\[[^\]]+\]/.test(candidate)) return false;
  if (/company name|job title|dates|phone|email/i.test(candidate)) return false;
  return candidate.length >= 24;
}

function getLatexSectionAt(sourceTex: string, position: number) {
  const before = sourceTex.slice(0, position);
  const matches = Array.from(before.matchAll(/\\section\*?\{([^{}]+)\}/g));
  const last = matches.at(-1);
  return normalizeSectionName(last?.[1] ?? "resume");
}

function findCommandArgument(sourceTex: string, openingBrace: number) {
  let depth = 0;
  for (let index = openingBrace; index < sourceTex.length; index += 1) {
    const char = sourceTex[index];
    if (char === "\\") {
      index += 1;
      continue;
    }
    if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        return {
          contentStart: openingBrace + 1,
          contentEnd: index,
          argumentEnd: index + 1,
        };
      }
    }
  }
  return null;
}

function bestSupportedCandidate(
  originalLatex: string,
  section: string,
  bullets: MarkdownBullet[],
  used: Set<number>
) {
  if (/\\href\s*\{/.test(originalLatex)) {
    return null;
  }

  const originalPlain = latexToPlain(originalLatex);
  let best: { index: number; score: number } | null = null;

  for (let index = 0; index < bullets.length; index += 1) {
    if (used.has(index)) continue;
    const bullet = bullets[index];
    if (!candidateLooksSafe(bullet.text)) continue;

    const sectionBonus = bullet.section === section ? 0.12 : 0;
    const score = overlapScore(originalPlain, bullet.text) + sectionBonus;
    if (!best || score > best.score) {
      best = { index, score };
    }
  }

  if (!best || best.score < 0.34) return null;
  used.add(best.index);
  return bullets[best.index].text;
}

function patchResumeItemsFromMarkdown(sourceTex: string, markdown: string) {
  const begin = sourceTex.indexOf(String.raw`\begin{document}`);
  const end = sourceTex.lastIndexOf(String.raw`\end{document}`);
  if (begin === -1 || end === -1 || end <= begin) return null;

  const bullets = parseMarkdownBullets(markdown);
  if (bullets.length === 0) return null;

  const commandPattern = /\\resumeItem\s*\{/g;
  const used = new Set<number>();
  let output = "";
  let cursor = 0;
  let match: RegExpExecArray | null;

  while ((match = commandPattern.exec(sourceTex))) {
    if (match.index < begin || match.index > end) continue;

    const openingBrace = sourceTex.indexOf("{", match.index);
    if (openingBrace === -1) continue;
    const range = findCommandArgument(sourceTex, openingBrace);
    if (!range) continue;

    const originalLatex = sourceTex.slice(range.contentStart, range.contentEnd);
    const section = getLatexSectionAt(sourceTex, match.index);
    const candidate = bestSupportedCandidate(originalLatex, section, bullets, used);
    if (!candidate) continue;

    output += sourceTex.slice(cursor, range.contentStart);
    output += escapeLatex(candidate);
    cursor = range.contentEnd;
    commandPattern.lastIndex = range.argumentEnd;
  }

  if (cursor === 0) return null;
  output += sourceTex.slice(cursor);
  return output;
}

function renderTextLine(text: string) {
  const escaped = escapeLatex(text);
  if (text.includes("|") || / -- | - /.test(text)) {
    return String.raw`\textbf{${escaped}}\\[-1pt]`;
  }
  return String.raw`${escaped}\\[-1pt]`;
}

function renderResumeBody(markdown: string, options: RenderResumeBodyOptions = {}) {
  const lines = parseResumeLines(markdown);
  const output: string[] = [];
  let inItems = false;
  let seenHeading = false;
  let headerLines: string[] = [];
  const itemListStart = options.useResumeItemMacros
    ? String.raw`\resumeItemListStart`
    : String.raw`\begin{itemize}`;
  const itemListEnd = options.useResumeItemMacros
    ? String.raw`\resumeItemListEnd`
    : String.raw`\end{itemize}`;

  const closeItems = () => {
    if (!inItems) return;
    output.push(itemListEnd);
    inItems = false;
  };

  const flushHeader = () => {
    if (seenHeading || headerLines.length === 0) return;
    if (options.sourceHeaderTex?.trim()) {
      output.push(options.sourceHeaderTex.trim());
      headerLines = [];
      return;
    }

    const [name, ...contact] = headerLines;
    output.push(String.raw`\begin{center}`);
    output.push(String.raw`  \textbf{\huge \scshape ${escapeLatex(name)}}`);
    if (contact.length > 0) {
      output.push(String.raw`  \\ \vspace{2pt}`);
      output.push(String.raw`  ${escapeLatex(contact.join(" | "))}`);
    }
    output.push(String.raw`\end{center}`);
    output.push(String.raw`\vspace{-12pt}`);
    headerLines = [];
  };

  for (const line of lines) {
    if (line.kind === "blank") {
      closeItems();
      if (!seenHeading) flushHeader();
      continue;
    }

    if (line.kind === "heading") {
      closeItems();
      flushHeader();
      seenHeading = true;
      output.push("");
      output.push(String.raw`\section{${escapeLatex(line.text)}}`);
      continue;
    }

    if (!seenHeading && line.kind === "text") {
      headerLines.push(line.text);
      continue;
    }

    flushHeader();

    if (line.kind === "bullet") {
      if (!inItems) {
        output.push(itemListStart);
        inItems = true;
      }
      output.push(
        options.useResumeItemMacros
          ? String.raw`  \resumeItem{${escapeLatex(line.text)}}`
          : String.raw`  \item ${escapeLatex(line.text)}`
      );
      continue;
    }

    closeItems();
    output.push(renderTextLine(line.text));
  }

  closeItems();
  flushHeader();

  return output.join("\n").trim();
}

function replaceDocumentBody(sourceTex: string, body: string) {
  const begin = sourceTex.indexOf(String.raw`\begin{document}`);
  const end = sourceTex.lastIndexOf(String.raw`\end{document}`);
  if (begin === -1 || end === -1 || end <= begin) return null;

  const beforeDocument = sourceTex.slice(0, begin);
  return `${beforeDocument}${String.raw`\begin{document}`}\n\n${body}\n\n${String.raw`\end{document}`}\n`;
}

function extractSourceHeader(sourceTex: string) {
  const begin = sourceTex.indexOf(String.raw`\begin{document}`);
  const end = sourceTex.lastIndexOf(String.raw`\end{document}`);
  if (begin === -1 || end === -1 || end <= begin) return null;

  const bodyStart = begin + String.raw`\begin{document}`.length;
  const documentBody = sourceTex.slice(bodyStart, end);
  const firstSection = documentBody.search(/\\section\*?\s*\{/);
  if (firstSection === -1) return null;

  const header = documentBody.slice(0, firstSection).trim();
  return header || null;
}

function hasResumeItemMacros(sourceTex: string) {
  return (
    sourceTex.includes(String.raw`\resumeItemListStart`)
    && sourceTex.includes(String.raw`\resumeItem{`)
    && sourceTex.includes(String.raw`\resumeItemListEnd`)
  );
}

export function buildTailoredResumeTex(markdown: string, options: TailoredResumeTexOptions = {}) {
  const sourceTex = options.sourceTex?.trim();
  const patchedSource = sourceTex ? patchResumeItemsFromMarkdown(sourceTex, markdown) : null;
  if (patchedSource) {
    return `% Tailored for ${options.companyName ?? "job"} - ${options.jobTitle ?? "role"}\n${patchedSource}`;
  }
  if (sourceTex) {
    return `% Tailored for ${options.companyName ?? "job"} - ${options.jobTitle ?? "role"}\n${sourceTex}`;
  }

  const body = renderResumeBody(markdown, {
    sourceHeaderTex: sourceTex ? extractSourceHeader(sourceTex) : null,
    useResumeItemMacros: sourceTex ? hasResumeItemMacros(sourceTex) : false,
  });
  const sourceBased = sourceTex ? replaceDocumentBody(sourceTex, body) : null;
  if (sourceBased) {
    return `% Tailored for ${options.companyName ?? "job"} - ${options.jobTitle ?? "role"}\n${sourceBased}`;
  }

  return `% Tailored for ${options.companyName ?? "job"} - ${options.jobTitle ?? "role"}\n${DEFAULT_PREAMBLE}\n\\begin{document}\n\n${body}\n\n\\end{document}\n`;
}

function slugify(input: string) {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

export function tailoredResumeTexFileName(companyName?: string | null, jobTitle?: string | null) {
  const slug = slugify([companyName, jobTitle, "resume"].filter(Boolean).join(" "));
  return `${slug || "tailored-resume"}.tex`;
}

export function downloadTextFile(fileName: string, text: string, mimeType = "text/plain;charset=utf-8") {
  const documentRef = (globalThis as any).document;
  const windowRef = (globalThis as any).window;
  if (!documentRef || !windowRef) return;
  const blob = new Blob([text], { type: mimeType });
  const url = URL.createObjectURL(blob);
  try {
    const anchor = documentRef.createElement("a");
    anchor.href = url;
    anchor.download = fileName;
    anchor.rel = "noopener";
    anchor.click();
  } finally {
    windowRef.setTimeout(() => URL.revokeObjectURL(url), 120_000);
  }
}
